# DataFrames III - Filtering
- To **filter** means to select a subset of `DataFrame` rows that satisfy a condition.

In [19]:
import polars as pl

## Introducing the Dataset
- The `coffee_sales` CSV stores transactions for a fictional coffee shop.
- Polars will import the `time_of_purchase` column as strings.
- Use the `try_parse_dates` parameter to parse string columns as datetimes.

In [20]:
coffees = pl.read_csv("coffee_sales.csv", try_parse_dates=True).sort("time_of_purchase")

## The filter Method
- The `filter` method extracts a subset of `DataFrame` rows that satisfy a condition.
- The `filter` method accepts a Boolean expression (one that produces a column of Booleans).
- The `filter` method will keep the rows with a value of `true` and exclude the rows with a value of `false`.
- Polars supports the standard comparison operators like `==`, `!=`, `>`, `<`, and more.
- Boolean comparisons on `null` will evaluate to `null`.

In [21]:
coffees.select(
    pl.col("coffee_name"),
    (pl.col("coffee_name") == "Flat White").alias("is_flat_white"),
)

shape: (1_000, 2)
┌─────────────┬───────────────┐
│ coffee_name ┆ is_flat_white │
│ ---         ┆ ---           │
│ str         ┆ bool          │
╞═════════════╪═══════════════╡
│ Latte       ┆ false         │
│ Flat White  ┆ true          │
│ Mocha       ┆ false         │
│ null        ┆ null          │
│ Flat White  ┆ true          │
│ …           ┆ …             │
│ Macchiato   ┆ false         │
│ Americano   ┆ false         │
│ Espresso    ┆ false         │
│ Latte       ┆ false         │
│ Espresso    ┆ false         │
└─────────────┴───────────────┘

- The `==` operator compares the equality of every row value with a constant.
- The `eq` method is equivalent to `==`.

In [22]:
coffees.select(
    pl.col("coffee_name"),
    (pl.col("coffee_name").eq("Flat White")).alias("is_flat_white"),
)

shape: (1_000, 2)
┌─────────────┬───────────────┐
│ coffee_name ┆ is_flat_white │
│ ---         ┆ ---           │
│ str         ┆ bool          │
╞═════════════╪═══════════════╡
│ Latte       ┆ false         │
│ Flat White  ┆ true          │
│ Mocha       ┆ false         │
│ null        ┆ null          │
│ Flat White  ┆ true          │
│ …           ┆ …             │
│ Macchiato   ┆ false         │
│ Americano   ┆ false         │
│ Espresso    ┆ false         │
│ Latte       ┆ false         │
│ Espresso    ┆ false         │
└─────────────┴───────────────┘

In [23]:
is_flat_white = pl.col("coffee_name").eq("Flat White")
coffees.filter(is_flat_white)

shape: (155, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true  ┆ Christopher ┆ 4.29  │
│ 02:39:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Danielle    ┆ 3.74  │
│ 15:07:27           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Joshua      ┆ 2.6   │
│ 01:50:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-03         ┆ Midtown West ┆ Flat White  ┆ Soy       ┆ 12   ┆ true  ┆ Anthony     ┆ 3.69  │
│ 10:57:47           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-07         ┆ Downtown     ┆ Flat White  ┆ 2%        ┆ 16   ┆ false ┆ Jill        ┆ 5.08  │
│ 23:54:11           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-01         ┆ Midtown West ┆ Flat White  ┆ Oat       ┆ 16   ┆ false ┆ Erica       ┆ 6.21  │
│ 03:42:07           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-02         ┆ Downtown     ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Erica       ┆ 5.76  │
│ 13:54:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ East Village ┆ Flat White  ┆ Coconut   ┆ 16   ┆ false ┆ Angel       ┆ 5.23  │
│ 11:23:23           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 3.47  │
│ 14:36:47           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ East Village ┆ Flat White  ┆ Oat       ┆ 20   ┆ false ┆ Erica       ┆ 4.75  │
│ 14:51:19           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- Pass the Boolean expression to the `filter` method.

In [24]:
coffees.filter(pl.col("coffee_name") == "Flat White")

shape: (155, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true  ┆ Christopher ┆ 4.29  │
│ 02:39:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Danielle    ┆ 3.74  │
│ 15:07:27           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Joshua      ┆ 2.6   │
│ 01:50:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-03         ┆ Midtown West ┆ Flat White  ┆ Soy       ┆ 12   ┆ true  ┆ Anthony     ┆ 3.69  │
│ 10:57:47           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-07         ┆ Downtown     ┆ Flat White  ┆ 2%        ┆ 16   ┆ false ┆ Jill        ┆ 5.08  │
│ 23:54:11           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-01         ┆ Midtown West ┆ Flat White  ┆ Oat       ┆ 16   ┆ false ┆ Erica       ┆ 6.21  │
│ 03:42:07           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-02         ┆ Downtown     ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Erica       ┆ 5.76  │
│ 13:54:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ East Village ┆ Flat White  ┆ Coconut   ┆ 16   ┆ false ┆ Angel       ┆ 5.23  │
│ 11:23:23           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 3.47  │
│ 14:36:47           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ East Village ┆ Flat White  ┆ Oat       ┆ 20   ┆ false ┆ Erica       ┆ 4.75  │
│ 14:51:19           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

In [25]:
coffees.filter(pl.col("coffee_name").eq("Flat White"))

shape: (155, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true  ┆ Christopher ┆ 4.29  │
│ 02:39:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Danielle    ┆ 3.74  │
│ 15:07:27           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Joshua      ┆ 2.6   │
│ 01:50:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-03         ┆ Midtown West ┆ Flat White  ┆ Soy       ┆ 12   ┆ true  ┆ Anthony     ┆ 3.69  │
│ 10:57:47           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-07         ┆ Downtown     ┆ Flat White  ┆ 2%        ┆ 16   ┆ false ┆ Jill        ┆ 5.08  │
│ 23:54:11           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-01         ┆ Midtown West ┆ Flat White  ┆ Oat       ┆ 16   ┆ false ┆ Erica       ┆ 6.21  │
│ 03:42:07           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-02         ┆ Downtown     ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Erica       ┆ 5.76  │
│ 13:54:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ East Village ┆ Flat White  ┆ Coconut   ┆ 16   ┆ false ┆ Angel       ┆ 5.23  │
│ 11:23:23           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 3.47  │
│ 14:36:47           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ East Village ┆ Flat White  ┆ Oat       ┆ 20   ┆ false ┆ Erica       ┆ 4.75  │
│ 14:51:19           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

In [26]:
coffees.filter(pl.col("location") == "SoHo")

shape: (191, 8)
┌─────────────────────┬──────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase    ┆ location ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                 ┆ ---      ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]        ┆ str      ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞═════════════════════╪══════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01 15:07:27 ┆ SoHo     ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Danielle    ┆ 3.74  │
│ 2025-01-02 06:17:11 ┆ SoHo     ┆ Mocha       ┆ Coconut   ┆ 20   ┆ true  ┆ Joshua      ┆ 5.67  │
│ 2025-01-03 05:30:19 ┆ SoHo     ┆ Macchiato   ┆ Oat       ┆ 12   ┆ true  ┆ Christopher ┆ 2.9   │
│ 2025-01-09 10:29:37 ┆ SoHo     ┆ Latte       ┆ 2%        ┆ 16   ┆ false ┆ Jill        ┆ 6.21  │
│ 2025-01-09 21:33:25 ┆ SoHo     ┆ Mocha       ┆ Coconut   ┆ 20   ┆ true  ┆ Christopher ┆ 4.71  │
│ …                   ┆ …        ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-04 23:36:46 ┆ SoHo     ┆ Espresso    ┆ Whole     ┆ 16   ┆ false ┆ Christopher ┆ 4.64  │
│ 2025-06-05 14:52:19 ┆ SoHo     ┆ Mocha       ┆ Coconut   ┆ 16   ┆ false ┆ Erica       ┆ 6.01  │
│ 2025-06-06 14:36:47 ┆ SoHo     ┆ Flat White  ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 3.47  │
│ 2025-06-06 15:50:35 ┆ SoHo     ┆ Americano   ┆ 2%        ┆ 16   ┆ false ┆ Jeffrey     ┆ 4.16  │
│ 2025-06-06 19:12:31 ┆ SoHo     ┆ Latte       ┆ Coconut   ┆ 16   ┆ true  ┆ Erica       ┆ 4.96  │
└─────────────────────┴──────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

### Further Reading
- https://docs.pola.rs/user-guide/getting-started/#filter
- https://docs.pola.rs/user-guide/concepts/expressions-and-contexts/#filter
- https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.filter.html

## Filtering with Mathematical Operators

In [27]:
coffees.filter(pl.col("milk_type") != "Oat")

shape: (840, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.85  │
│ 07:52:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ null        ┆ Soy       ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.05  │
│ 10:02:41           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.83  │
│ 16:31:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ East Village ┆ Espresso    ┆ 2%        ┆ 20   ┆ true  ┆ Joshua      ┆ 4.79  │
│ 03:28:39           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-07         ┆ Midtown West ┆ Espresso    ┆ Almond    ┆ 12   ┆ true  ┆ Joshua      ┆ 4.54  │
│ 04:13:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel       ┆ 4.82  │
│ 10:28:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle    ┆ 5.17  │
│ 06:12:20           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- The `!=` operator compares the inequality of every column value with a constant.
- The `ne` method is the equivalent method.

In [28]:
coffees.filter(pl.col("milk_type").ne("Oat"))

shape: (840, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.85  │
│ 07:52:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ null        ┆ Soy       ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.05  │
│ 10:02:41           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.83  │
│ 16:31:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ East Village ┆ Espresso    ┆ 2%        ┆ 20   ┆ true  ┆ Joshua      ┆ 4.79  │
│ 03:28:39           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-07         ┆ Midtown West ┆ Espresso    ┆ Almond    ┆ 12   ┆ true  ┆ Joshua      ┆ 4.54  │
│ 04:13:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel       ┆ 4.82  │
│ 10:28:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle    ┆ 5.17  │
│ 06:12:20           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- Polars supports the standard mathematical operators for comparisons:
    - `<` or `lt` for less than
    - `<=` or `le` for less than or equal to
    - `>` or `gt` for greater than
    - `>=` or `ge` for greater than or equal to

In [30]:
coffees.filter(pl.col("price") > 5)
coffees.filter(pl.col("price").gt(5))

shape: (383, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬──────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista  ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---      ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str      ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪══════════╪═══════╡
│ 2025-01-01 07:52:54 ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey  ┆ 5.85  │
│ 2025-01-01 10:02:41 ┆ Midtown West ┆ null        ┆ Soy       ┆ 12   ┆ false ┆ Jeffrey  ┆ 5.05  │
│ 2025-01-02 06:17:11 ┆ SoHo         ┆ Mocha       ┆ Coconut   ┆ 20   ┆ true  ┆ Joshua   ┆ 5.67  │
│ 2025-01-02 09:30:42 ┆ East Village ┆ Macchiato   ┆ Whole     ┆ 12   ┆ false ┆ Robert   ┆ 6.24  │
│ 2025-01-02 19:24:47 ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 12   ┆ false ┆ Jill     ┆ 5.69  │
│ …                   ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …        ┆ …     │
│ 2025-06-06 11:23:23 ┆ East Village ┆ Flat White  ┆ Coconut   ┆ 16   ┆ false ┆ Angel    ┆ 5.23  │
│ 2025-06-06 17:29:25 ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 12   ┆ false ┆ Jeffrey  ┆ 5.96  │
│ 2025-06-06 21:39:23 ┆ Downtown     ┆ Macchiato   ┆ Whole     ┆ 12   ┆ false ┆ Robert   ┆ 6.26  │
│ 2025-06-07 10:21:56 ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle ┆ 6.49  │
│ 2025-06-08 06:12:20 ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle ┆ 5.17  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴──────────┴───────┘

In [31]:
coffees.filter(pl.col("price") < 5)
coffees.filter(pl.col("price").lt(5))

shape: (617, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true  ┆ Christopher ┆ 4.29  │
│ 02:39:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Danielle    ┆ 3.74  │
│ 15:07:27           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.83  │
│ 16:31:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Joshua      ┆ 2.6   │
│ 01:50:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-06         ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true  ┆ Danielle    ┆ 3.33  │
│ 22:28:52           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ Midtown West ┆ Espresso    ┆ Almond    ┆ 12   ┆ true  ┆ Joshua      ┆ 4.54  │
│ 04:13:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel       ┆ 4.82  │
│ 10:28:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

In [32]:
coffees.filter(pl.col("price") >= 5)
coffees.filter(pl.col("price").gt(5))

shape: (383, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬──────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista  ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---      ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str      ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪══════════╪═══════╡
│ 2025-01-01 07:52:54 ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey  ┆ 5.85  │
│ 2025-01-01 10:02:41 ┆ Midtown West ┆ null        ┆ Soy       ┆ 12   ┆ false ┆ Jeffrey  ┆ 5.05  │
│ 2025-01-02 06:17:11 ┆ SoHo         ┆ Mocha       ┆ Coconut   ┆ 20   ┆ true  ┆ Joshua   ┆ 5.67  │
│ 2025-01-02 09:30:42 ┆ East Village ┆ Macchiato   ┆ Whole     ┆ 12   ┆ false ┆ Robert   ┆ 6.24  │
│ 2025-01-02 19:24:47 ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 12   ┆ false ┆ Jill     ┆ 5.69  │
│ …                   ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …        ┆ …     │
│ 2025-06-06 11:23:23 ┆ East Village ┆ Flat White  ┆ Coconut   ┆ 16   ┆ false ┆ Angel    ┆ 5.23  │
│ 2025-06-06 17:29:25 ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 12   ┆ false ┆ Jeffrey  ┆ 5.96  │
│ 2025-06-06 21:39:23 ┆ Downtown     ┆ Macchiato   ┆ Whole     ┆ 12   ┆ false ┆ Robert   ┆ 6.26  │
│ 2025-06-07 10:21:56 ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle ┆ 6.49  │
│ 2025-06-08 06:12:20 ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle ┆ 5.17  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴──────────┴───────┘

In [33]:
coffees.filter(pl.col("price") <= 5)
coffees.filter(pl.col("price").le(5))

shape: (617, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true  ┆ Christopher ┆ 4.29  │
│ 02:39:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Danielle    ┆ 3.74  │
│ 15:07:27           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.83  │
│ 16:31:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Joshua      ┆ 2.6   │
│ 01:50:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-06         ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true  ┆ Danielle    ┆ 3.33  │
│ 22:28:52           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ Midtown West ┆ Espresso    ┆ Almond    ┆ 12   ┆ true  ┆ Joshua      ┆ 4.54  │
│ 04:13:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel       ┆ 4.82  │
│ 10:28:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

### Further Reading
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.eq.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.ne.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.lt.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.le.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.gt.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.ge.html

## Filtering with Missing Values
- The `filter` method excludes `null` values by default.
- Polars has a family of comparison methods ending in `_missing` that include null values.
- For example, the `eq_missing` method compares the equality of a `null` with the argument.

In [34]:
coffees.null_count()

shape: (1, 8)
┌──────────────────┬──────────┬─────────────┬───────────┬──────┬──────┬─────────┬───────┐
│ time_of_purchase ┆ location ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista ┆ price │
│ ---              ┆ ---      ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---     ┆ ---   │
│ u32              ┆ u32      ┆ u32         ┆ u32       ┆ u32  ┆ u32  ┆ u32     ┆ u32   │
╞══════════════════╪══════════╪═════════════╪═══════════╪══════╪══════╪═════════╪═══════╡
│ 0                ┆ 0        ┆ 6           ┆ 0         ┆ 0    ┆ 0    ┆ 0       ┆ 0     │
└──────────────────┴──────────┴─────────────┴───────────┴──────┴──────┴─────────┴───────┘

In [36]:
coffees.filter(pl.col("coffee_name").ne_missing("Mocha"))

shape: (866, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true  ┆ Christopher ┆ 4.29  │
│ 02:39:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ null        ┆ Soy       ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.05  │
│ 10:02:41           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Danielle    ┆ 3.74  │
│ 15:07:27           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.83  │
│ 16:31:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-07         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 6.49  │
│ 10:21:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel       ┆ 4.82  │
│ 10:28:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle    ┆ 5.17  │
│ 06:12:20           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

In [39]:
coffees.filter(pl.col("coffee_name").eq(None))

/var/folders/z3/8v7jzndj50s8m09njkvjg18w0000gn/T/ipykernel_96509/4117428144.py:1: UserWarning: Comparisons with None always result in null. Consider using `.is_null()` or `.is_not_null()`.
  coffees.filter(pl.col("coffee_name").eq(None))

shape: (0, 8)
┌──────────────────┬──────────┬─────────────┬───────────┬──────┬──────┬─────────┬───────┐
│ time_of_purchase ┆ location ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista ┆ price │
│ ---              ┆ ---      ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---     ┆ ---   │
│ datetime[μs]     ┆ str      ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str     ┆ f64   │
╞══════════════════╪══════════╪═════════════╪═══════════╪══════╪══════╪═════════╪═══════╡
└──────────────────┴──────────┴─────────────┴───────────┴──────┴──────┴─────────┴───────┘

In [40]:
coffees.filter(pl.col("coffee_name").eq_missing(None))

shape: (6, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ null        ┆ Soy       ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.05  │
│ 10:02:41           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-07         ┆ Downtown     ┆ null        ┆ Oat       ┆ 16   ┆ false ┆ Christopher ┆ 3.92  │
│ 00:36:36           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-29         ┆ Downtown     ┆ null        ┆ Oat       ┆ 16   ┆ true  ┆ Jill        ┆ 6.09  │
│ 15:43:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-02-22         ┆ SoHo         ┆ null        ┆ 2%        ┆ 20   ┆ true  ┆ Robert      ┆ 2.72  │
│ 23:58:14           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-04-09         ┆ Downtown     ┆ null        ┆ Whole     ┆ 16   ┆ true  ┆ Angel       ┆ 2.8   │
│ 22:00:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-05-10         ┆ SoHo         ┆ null        ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.4   │
│ 16:28:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

In [41]:
coffees.filter(pl.col("coffee_name").is_null())

shape: (6, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ null        ┆ Soy       ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.05  │
│ 10:02:41           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-07         ┆ Downtown     ┆ null        ┆ Oat       ┆ 16   ┆ false ┆ Christopher ┆ 3.92  │
│ 00:36:36           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-29         ┆ Downtown     ┆ null        ┆ Oat       ┆ 16   ┆ true  ┆ Jill        ┆ 6.09  │
│ 15:43:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-02-22         ┆ SoHo         ┆ null        ┆ 2%        ┆ 20   ┆ true  ┆ Robert      ┆ 2.72  │
│ 23:58:14           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-04-09         ┆ Downtown     ┆ null        ┆ Whole     ┆ 16   ┆ true  ┆ Angel       ┆ 2.8   │
│ 22:00:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-05-10         ┆ SoHo         ┆ null        ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.4   │
│ 16:28:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

In [44]:
coffees.filter(pl.col("coffee_name").ne_missing(None))

shape: (994, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true  ┆ Christopher ┆ 4.29  │
│ 02:39:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.85  │
│ 07:52:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Danielle    ┆ 3.74  │
│ 15:07:27           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.83  │
│ 16:31:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-07         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 6.49  │
│ 10:21:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel       ┆ 4.82  │
│ 10:28:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle    ┆ 5.17  │
│ 06:12:20           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- We can pass in `None` to compare equality with `null`/missing values...

In [45]:
coffees.filter(pl.col("coffee_name").is_not_null())

shape: (994, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true  ┆ Christopher ┆ 4.29  │
│ 02:39:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.85  │
│ 07:52:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Danielle    ┆ 3.74  │
│ 15:07:27           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.83  │
│ 16:31:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-07         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 6.49  │
│ 10:21:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel       ┆ 4.82  │
│ 10:28:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle    ┆ 5.17  │
│ 06:12:20           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- ...but the more idiomatic solution is the `is_null` method.
- The `is_null` method returns a Boolean `Series` where a true represents a missing value.

### Further Reading
- https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.null_count.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.ne_missing.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.eq_missing.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.is_null.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.is_not_null.html

## Filtering with Boolean Columns
- Polars prints its Booleans in lowercase (`true`, `false`).
- Python's Booleans have a capital first letter (`True`, `False`)
- We _could_ compare every value in a Boolean column to `True`.
- But a cleaner approach is to pass the Boolean column directly to the `filter` method.

In [49]:
coffees.filter(pl.col("iced") == True)
coffees.filter(pl.col("iced").eq(True))
coffees.filter(pl.col("iced"))

shape: (464, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬──────┬─────────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista     ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---         ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str         ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪══════╪═════════════╪═══════╡
│ 2025-01-01 01:53:30 ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 3.1   │
│ 2025-01-01 02:39:54 ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true ┆ Christopher ┆ 4.29  │
│ 2025-01-02 01:50:26 ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true ┆ Joshua      ┆ 2.6   │
│ 2025-01-02 03:28:39 ┆ East Village ┆ Espresso    ┆ 2%        ┆ 20   ┆ true ┆ Joshua      ┆ 4.79  │
│ 2025-01-02 06:17:11 ┆ SoHo         ┆ Mocha       ┆ Coconut   ┆ 20   ┆ true ┆ Joshua      ┆ 5.67  │
│ …                   ┆ …            ┆ …           ┆ …         ┆ …    ┆ …    ┆ …           ┆ …     │
│ 2025-06-05 07:39:21 ┆ Midtown West ┆ Americano   ┆ Coconut   ┆ 12   ┆ true ┆ Anthony     ┆ 4.79  │
│ 2025-06-06 10:01:56 ┆ Uptown       ┆ Americano   ┆ 2%        ┆ 16   ┆ true ┆ Jill        ┆ 5.59  │
│ 2025-06-06 19:12:31 ┆ SoHo         ┆ Latte       ┆ Coconut   ┆ 16   ┆ true ┆ Erica       ┆ 4.96  │
│ 2025-06-06 22:28:52 ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true ┆ Danielle    ┆ 3.33  │
│ 2025-06-07 04:13:09 ┆ Midtown West ┆ Espresso    ┆ Almond    ┆ 12   ┆ true ┆ Joshua      ┆ 4.54  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴──────┴─────────────┴───────┘

## Applying And Logic
- The `&` operator applies AND logic between two Boolean expressions.
- Both conditions must be met for the evaluation to be true.
- The AND (`&`) logic is called "conjunction" in mathematics.

In [53]:
coffees.filter((pl.col("milk_type") == "Soy") & (pl.col("size") > 10))

shape: (172, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ null        ┆ Soy       ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.05  │
│ 10:02:41           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 12   ┆ false ┆ Jill        ┆ 5.69  │
│ 19:24:47           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Downtown     ┆ Latte       ┆ Soy       ┆ 16   ┆ false ┆ Anthony     ┆ 2.53  │
│ 21:03:50           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-03         ┆ Midtown West ┆ Flat White  ┆ Soy       ┆ 12   ┆ true  ┆ Anthony     ┆ 3.69  │
│ 10:57:47           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-04         ┆ SoHo         ┆ Americano   ┆ Soy       ┆ 16   ┆ false ┆ Christopher ┆ 2.85  │
│ 03:04:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-04         ┆ Uptown       ┆ Espresso    ┆ Soy       ┆ 20   ┆ true  ┆ Jeffrey     ┆ 5.73  │
│ 10:34:43           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-04         ┆ East Village ┆ Latte       ┆ Soy       ┆ 12   ┆ false ┆ Anthony     ┆ 4.35  │
│ 22:10:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 12   ┆ false ┆ Robert      ┆ 3.07  │
│ 03:25:24           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true  ┆ Danielle    ┆ 3.33  │
│ 22:28:52           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

In [59]:
coffees.filter(pl.col("milk_type").eq("Soy") & pl.col("size").gt(10))

shape: (172, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ null        ┆ Soy       ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.05  │
│ 10:02:41           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 12   ┆ false ┆ Jill        ┆ 5.69  │
│ 19:24:47           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Downtown     ┆ Latte       ┆ Soy       ┆ 16   ┆ false ┆ Anthony     ┆ 2.53  │
│ 21:03:50           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-03         ┆ Midtown West ┆ Flat White  ┆ Soy       ┆ 12   ┆ true  ┆ Anthony     ┆ 3.69  │
│ 10:57:47           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-04         ┆ SoHo         ┆ Americano   ┆ Soy       ┆ 16   ┆ false ┆ Christopher ┆ 2.85  │
│ 03:04:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-04         ┆ Uptown       ┆ Espresso    ┆ Soy       ┆ 20   ┆ true  ┆ Jeffrey     ┆ 5.73  │
│ 10:34:43           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-04         ┆ East Village ┆ Latte       ┆ Soy       ┆ 12   ┆ false ┆ Anthony     ┆ 4.35  │
│ 22:10:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 12   ┆ false ┆ Robert      ┆ 3.07  │
│ 03:25:24           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true  ┆ Danielle    ┆ 3.33  │
│ 22:28:52           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

In [60]:
with_soy_milk = pl.col("milk_type").eq("Soy")
with_size_treater_than_10 = pl.col("size").gt(10)
coffees.filter(with_soy_milk & with_size_treater_than_10)

shape: (172, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ null        ┆ Soy       ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.05  │
│ 10:02:41           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 12   ┆ false ┆ Jill        ┆ 5.69  │
│ 19:24:47           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Downtown     ┆ Latte       ┆ Soy       ┆ 16   ┆ false ┆ Anthony     ┆ 2.53  │
│ 21:03:50           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-03         ┆ Midtown West ┆ Flat White  ┆ Soy       ┆ 12   ┆ true  ┆ Anthony     ┆ 3.69  │
│ 10:57:47           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-04         ┆ SoHo         ┆ Americano   ┆ Soy       ┆ 16   ┆ false ┆ Christopher ┆ 2.85  │
│ 03:04:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-04         ┆ Uptown       ┆ Espresso    ┆ Soy       ┆ 20   ┆ true  ┆ Jeffrey     ┆ 5.73  │
│ 10:34:43           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-04         ┆ East Village ┆ Latte       ┆ Soy       ┆ 12   ┆ false ┆ Anthony     ┆ 4.35  │
│ 22:10:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 12   ┆ false ┆ Robert      ┆ 3.07  │
│ 03:25:24           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true  ┆ Danielle    ┆ 3.33  │
│ 22:28:52           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- Wrap each expression in parentheses to isolate it. Otherwise, Polars will get confused.
- The following example extracts rows with a `milk_type` of "Soy" and a `size` greater than 18.

- Methods allow the omission of parentheses.
- Alternatively, assign the expressions to variables.

- The `filter` method supports any number of expressions.

In [61]:
coffees.filter(pl.col("milk_type").eq("Soy") & pl.col("size").gt(10) & pl.col("iced"))

shape: (81, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬──────┬─────────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista     ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---         ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str         ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪══════╪═════════════╪═══════╡
│ 2025-01-01 01:53:30 ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 3.1   │
│ 2025-01-03 10:57:47 ┆ Midtown West ┆ Flat White  ┆ Soy       ┆ 12   ┆ true ┆ Anthony     ┆ 3.69  │
│ 2025-01-08 10:17:29 ┆ East Village ┆ Macchiato   ┆ Soy       ┆ 12   ┆ true ┆ Patricia    ┆ 6.38  │
│ 2025-01-08 12:28:11 ┆ Uptown       ┆ Espresso    ┆ Soy       ┆ 12   ┆ true ┆ Robert      ┆ 3.79  │
│ 2025-01-09 23:22:17 ┆ SoHo         ┆ Mocha       ┆ Soy       ┆ 12   ┆ true ┆ Danielle    ┆ 3.93  │
│ …                   ┆ …            ┆ …           ┆ …         ┆ …    ┆ …    ┆ …           ┆ …     │
│ 2025-05-29 17:02:49 ┆ Downtown     ┆ Americano   ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 4.16  │
│ 2025-05-30 05:55:46 ┆ Downtown     ┆ Latte       ┆ Soy       ┆ 16   ┆ true ┆ Patricia    ┆ 4.98  │
│ 2025-06-02 02:43:45 ┆ East Village ┆ Mocha       ┆ Soy       ┆ 16   ┆ true ┆ Patricia    ┆ 5.81  │
│ 2025-06-04 10:34:43 ┆ Uptown       ┆ Espresso    ┆ Soy       ┆ 20   ┆ true ┆ Jeffrey     ┆ 5.73  │
│ 2025-06-06 22:28:52 ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true ┆ Danielle    ┆ 3.33  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴──────┴─────────────┴───────┘

- As an alternative to the `&` symbol, we can also pass sequential Boolean expressions to the `filter` method.

In [62]:
coffees.filter(pl.col("milk_type").eq("Soy"), pl.col("size").gt(10), pl.col("iced"))

shape: (81, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬──────┬─────────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista     ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---         ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str         ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪══════╪═════════════╪═══════╡
│ 2025-01-01 01:53:30 ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 3.1   │
│ 2025-01-03 10:57:47 ┆ Midtown West ┆ Flat White  ┆ Soy       ┆ 12   ┆ true ┆ Anthony     ┆ 3.69  │
│ 2025-01-08 10:17:29 ┆ East Village ┆ Macchiato   ┆ Soy       ┆ 12   ┆ true ┆ Patricia    ┆ 6.38  │
│ 2025-01-08 12:28:11 ┆ Uptown       ┆ Espresso    ┆ Soy       ┆ 12   ┆ true ┆ Robert      ┆ 3.79  │
│ 2025-01-09 23:22:17 ┆ SoHo         ┆ Mocha       ┆ Soy       ┆ 12   ┆ true ┆ Danielle    ┆ 3.93  │
│ …                   ┆ …            ┆ …           ┆ …         ┆ …    ┆ …    ┆ …           ┆ …     │
│ 2025-05-29 17:02:49 ┆ Downtown     ┆ Americano   ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 4.16  │
│ 2025-05-30 05:55:46 ┆ Downtown     ┆ Latte       ┆ Soy       ┆ 16   ┆ true ┆ Patricia    ┆ 4.98  │
│ 2025-06-02 02:43:45 ┆ East Village ┆ Mocha       ┆ Soy       ┆ 16   ┆ true ┆ Patricia    ┆ 5.81  │
│ 2025-06-04 10:34:43 ┆ Uptown       ┆ Espresso    ┆ Soy       ┆ 20   ┆ true ┆ Jeffrey     ┆ 5.73  │
│ 2025-06-06 22:28:52 ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true ┆ Danielle    ┆ 3.33  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴──────┴─────────────┴───────┘

- The `and_` method is equivalent to the `&` operator.
- Polars chose these method names to avoid conflicts with Python's built-in keywords (`and`, `or` ,`not`).

In [63]:
coffees.filter(
    pl.col("milk_type").eq("Soy").and_(pl.col("size").gt(10)).and_(pl.col("iced"))
)

shape: (81, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬──────┬─────────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista     ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---         ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str         ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪══════╪═════════════╪═══════╡
│ 2025-01-01 01:53:30 ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 3.1   │
│ 2025-01-03 10:57:47 ┆ Midtown West ┆ Flat White  ┆ Soy       ┆ 12   ┆ true ┆ Anthony     ┆ 3.69  │
│ 2025-01-08 10:17:29 ┆ East Village ┆ Macchiato   ┆ Soy       ┆ 12   ┆ true ┆ Patricia    ┆ 6.38  │
│ 2025-01-08 12:28:11 ┆ Uptown       ┆ Espresso    ┆ Soy       ┆ 12   ┆ true ┆ Robert      ┆ 3.79  │
│ 2025-01-09 23:22:17 ┆ SoHo         ┆ Mocha       ┆ Soy       ┆ 12   ┆ true ┆ Danielle    ┆ 3.93  │
│ …                   ┆ …            ┆ …           ┆ …         ┆ …    ┆ …    ┆ …           ┆ …     │
│ 2025-05-29 17:02:49 ┆ Downtown     ┆ Americano   ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 4.16  │
│ 2025-05-30 05:55:46 ┆ Downtown     ┆ Latte       ┆ Soy       ┆ 16   ┆ true ┆ Patricia    ┆ 4.98  │
│ 2025-06-02 02:43:45 ┆ East Village ┆ Mocha       ┆ Soy       ┆ 16   ┆ true ┆ Patricia    ┆ 5.81  │
│ 2025-06-04 10:34:43 ┆ Uptown       ┆ Espresso    ┆ Soy       ┆ 20   ┆ true ┆ Jeffrey     ┆ 5.73  │
│ 2025-06-06 22:28:52 ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true ┆ Danielle    ┆ 3.33  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴──────┴─────────────┴───────┘

- These methods on expressions produce new expressions.

In [64]:
pl.col("milk_type").eq("Soy").and_(pl.col("size").gt(10)).and_(pl.col("iced"))

In [65]:
type(pl.col("milk_type").eq("Soy").and_(pl.col("size").gt(10)).and_(pl.col("iced")))

polars.expr.expr.Expr

### Further Reading
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.and_.html

## Keyword Argument Filtering
- The `filter` method supports keyword arguments.
- Pass the column name as the parameter and the comparison value as the argument.
- Keyword argument filtering only works for equality comparisons.
- The Polars team generally advises against this filtering approach. Use expressions.

In [68]:
coffees.filter(location="Uptown")
coffees.filter(pl.col("location") == "Uptown")

shape: (174, 8)
┌─────────────────────┬──────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase    ┆ location ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                 ┆ ---      ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]        ┆ str      ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞═════════════════════╪══════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01 02:39:54 ┆ Uptown   ┆ Flat White  ┆ Oat       ┆ 20   ┆ true  ┆ Christopher ┆ 4.29  │
│ 2025-01-02 01:50:26 ┆ Uptown   ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Joshua      ┆ 2.6   │
│ 2025-01-02 12:27:29 ┆ Uptown   ┆ Macchiato   ┆ Coconut   ┆ 16   ┆ true  ┆ Joshua      ┆ 3.89  │
│ 2025-01-02 23:18:27 ┆ Uptown   ┆ Americano   ┆ Coconut   ┆ 20   ┆ false ┆ Anthony     ┆ 4.08  │
│ 2025-01-04 08:21:33 ┆ Uptown   ┆ Americano   ┆ Oat       ┆ 16   ┆ true  ┆ Joshua      ┆ 4.52  │
│ …                   ┆ …        ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-02 08:35:29 ┆ Uptown   ┆ Espresso    ┆ Oat       ┆ 16   ┆ false ┆ Angel       ┆ 3.81  │
│ 2025-06-04 10:34:43 ┆ Uptown   ┆ Espresso    ┆ Soy       ┆ 20   ┆ true  ┆ Jeffrey     ┆ 5.73  │
│ 2025-06-06 10:01:56 ┆ Uptown   ┆ Americano   ┆ 2%        ┆ 16   ┆ true  ┆ Jill        ┆ 5.59  │
│ 2025-06-06 22:28:52 ┆ Uptown   ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true  ┆ Danielle    ┆ 3.33  │
│ 2025-06-08 13:34:09 ┆ Uptown   ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
└─────────────────────┴──────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

In [74]:
coffees.filter(location="Uptown", barista="Danielle")

shape: (19, 8)
┌─────────────────────┬──────────┬─────────────┬───────────┬──────┬───────┬──────────┬───────┐
│ time_of_purchase    ┆ location ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista  ┆ price │
│ ---                 ┆ ---      ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---      ┆ ---   │
│ datetime[μs]        ┆ str      ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str      ┆ f64   │
╞═════════════════════╪══════════╪═════════════╪═══════════╪══════╪═══════╪══════════╪═══════╡
│ 2025-01-08 19:36:59 ┆ Uptown   ┆ Espresso    ┆ Soy       ┆ 12   ┆ false ┆ Danielle ┆ 4.57  │
│ 2025-01-23 05:45:42 ┆ Uptown   ┆ Americano   ┆ Coconut   ┆ 20   ┆ false ┆ Danielle ┆ 2.77  │
│ 2025-01-23 09:31:53 ┆ Uptown   ┆ Mocha       ┆ Oat       ┆ 12   ┆ false ┆ Danielle ┆ 3.33  │
│ 2025-01-26 17:17:32 ┆ Uptown   ┆ Mocha       ┆ Whole     ┆ 20   ┆ false ┆ Danielle ┆ 6.3   │
│ 2025-02-07 06:02:22 ┆ Uptown   ┆ Mocha       ┆ Oat       ┆ 16   ┆ false ┆ Danielle ┆ 3.69  │
│ …                   ┆ …        ┆ …           ┆ …         ┆ …    ┆ …     ┆ …        ┆ …     │
│ 2025-05-10 21:39:44 ┆ Uptown   ┆ Americano   ┆ 2%        ┆ 16   ┆ true  ┆ Danielle ┆ 5.04  │
│ 2025-05-20 16:03:34 ┆ Uptown   ┆ Americano   ┆ 2%        ┆ 12   ┆ false ┆ Danielle ┆ 2.66  │
│ 2025-05-22 20:24:05 ┆ Uptown   ┆ Flat White  ┆ Almond    ┆ 20   ┆ true  ┆ Danielle ┆ 5.45  │
│ 2025-05-28 19:35:15 ┆ Uptown   ┆ Flat White  ┆ Almond    ┆ 20   ┆ true  ┆ Danielle ┆ 4.98  │
│ 2025-06-06 22:28:52 ┆ Uptown   ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true  ┆ Danielle ┆ 3.33  │
└─────────────────────┴──────────┴─────────────┴───────────┴──────┴───────┴──────────┴───────┘

- The following example filters row that have a `location` of "Uptown" and a `barista` of "Danielle".

- Boolean columns require an explicit `True` argument.
- The following example adds an additional criteria of a `True` in the `iced` column.

In [75]:
coffees.filter(iced=True)

shape: (464, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬──────┬─────────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista     ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---         ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str         ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪══════╪═════════════╪═══════╡
│ 2025-01-01 01:53:30 ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 3.1   │
│ 2025-01-01 02:39:54 ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true ┆ Christopher ┆ 4.29  │
│ 2025-01-02 01:50:26 ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true ┆ Joshua      ┆ 2.6   │
│ 2025-01-02 03:28:39 ┆ East Village ┆ Espresso    ┆ 2%        ┆ 20   ┆ true ┆ Joshua      ┆ 4.79  │
│ 2025-01-02 06:17:11 ┆ SoHo         ┆ Mocha       ┆ Coconut   ┆ 20   ┆ true ┆ Joshua      ┆ 5.67  │
│ …                   ┆ …            ┆ …           ┆ …         ┆ …    ┆ …    ┆ …           ┆ …     │
│ 2025-06-05 07:39:21 ┆ Midtown West ┆ Americano   ┆ Coconut   ┆ 12   ┆ true ┆ Anthony     ┆ 4.79  │
│ 2025-06-06 10:01:56 ┆ Uptown       ┆ Americano   ┆ 2%        ┆ 16   ┆ true ┆ Jill        ┆ 5.59  │
│ 2025-06-06 19:12:31 ┆ SoHo         ┆ Latte       ┆ Coconut   ┆ 16   ┆ true ┆ Erica       ┆ 4.96  │
│ 2025-06-06 22:28:52 ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true ┆ Danielle    ┆ 3.33  │
│ 2025-06-07 04:13:09 ┆ Midtown West ┆ Espresso    ┆ Almond    ┆ 12   ┆ true ┆ Joshua      ┆ 4.54  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴──────┴─────────────┴───────┘

## Applying or Logic
- The `|` operator applies OR logic between two Boolean expressions.
- At least one condition must be true for the final evaluation to be true.
- The OR (`|`) logic is called "disjunction" in mathematics.

In [76]:
coffees.filter((pl.col("price") <= 3) | (pl.col("location") == "Downtown"))

shape: (307, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.85  │
│ 07:52:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Joshua      ┆ 2.6   │
│ 01:50:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Downtown     ┆ Latte       ┆ Soy       ┆ 16   ┆ false ┆ Anthony     ┆ 2.53  │
│ 21:03:50           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-03         ┆ SoHo         ┆ Macchiato   ┆ Oat       ┆ 12   ┆ true  ┆ Christopher ┆ 2.9   │
│ 05:30:19           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-04         ┆ Uptown       ┆ Espresso    ┆ Soy       ┆ 20   ┆ false ┆ Joshua      ┆ 2.76  │
│ 18:46:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-05         ┆ Downtown     ┆ Macchiato   ┆ 2%        ┆ 12   ┆ false ┆ Robert      ┆ 5.49  │
│ 18:41:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Downtown     ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Jeffrey     ┆ 2.8   │
│ 07:47:07           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Downtown     ┆ Macchiato   ┆ Whole     ┆ 12   ┆ false ┆ Robert      ┆ 6.26  │
│ 21:39:23           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 6.49  │
│ 10:21:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- The next example filters row where `price` is less than or equal to 3 or `location` is equal to "Downtown".

In [80]:
coffees.filter((pl.col("price").le(3)) | (pl.col("location").eq("Downtown")))

shape: (307, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.85  │
│ 07:52:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Joshua      ┆ 2.6   │
│ 01:50:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Downtown     ┆ Latte       ┆ Soy       ┆ 16   ┆ false ┆ Anthony     ┆ 2.53  │
│ 21:03:50           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-03         ┆ SoHo         ┆ Macchiato   ┆ Oat       ┆ 12   ┆ true  ┆ Christopher ┆ 2.9   │
│ 05:30:19           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-04         ┆ Uptown       ┆ Espresso    ┆ Soy       ┆ 20   ┆ false ┆ Joshua      ┆ 2.76  │
│ 18:46:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-05         ┆ Downtown     ┆ Macchiato   ┆ 2%        ┆ 12   ┆ false ┆ Robert      ┆ 5.49  │
│ 18:41:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Downtown     ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Jeffrey     ┆ 2.8   │
│ 07:47:07           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Downtown     ┆ Macchiato   ┆ Whole     ┆ 12   ┆ false ┆ Robert      ┆ 6.26  │
│ 21:39:23           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 6.49  │
│ 10:21:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- The `le` method is equivalent to the `<=` symbol.
- Methods allow for the omission of parentheses.

In [82]:
coffees.filter(pl.col("price").le(3).or_(pl.col("location").eq("Downtown")))

shape: (307, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.85  │
│ 07:52:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Joshua      ┆ 2.6   │
│ 01:50:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Downtown     ┆ Latte       ┆ Soy       ┆ 16   ┆ false ┆ Anthony     ┆ 2.53  │
│ 21:03:50           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-03         ┆ SoHo         ┆ Macchiato   ┆ Oat       ┆ 12   ┆ true  ┆ Christopher ┆ 2.9   │
│ 05:30:19           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-04         ┆ Uptown       ┆ Espresso    ┆ Soy       ┆ 20   ┆ false ┆ Joshua      ┆ 2.76  │
│ 18:46:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-05         ┆ Downtown     ┆ Macchiato   ┆ 2%        ┆ 12   ┆ false ┆ Robert      ┆ 5.49  │
│ 18:41:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Downtown     ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Jeffrey     ┆ 2.8   │
│ 07:47:07           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Downtown     ┆ Macchiato   ┆ Whole     ┆ 12   ┆ false ┆ Robert      ┆ 6.26  │
│ 21:39:23           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 6.49  │
│ 10:21:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- The `or_` method is the equivalent of the `|` operator.
- We build up a complex expression that captures the same either/or logic.
- The Polars team chose this awkard name intentionally to avoid conflict/confusion with Python's `or` keyword.

- To simplify code, assign expressions to descriptive variables.

In [86]:
cheap_coffee = pl.col("price") <= 3
in_downtown = pl.col("location") == "Downtown"

coffees.filter(cheap_coffee | in_downtown)
coffees.filter(cheap_coffee.or_(in_downtown))

shape: (307, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.85  │
│ 07:52:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Joshua      ┆ 2.6   │
│ 01:50:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Downtown     ┆ Latte       ┆ Soy       ┆ 16   ┆ false ┆ Anthony     ┆ 2.53  │
│ 21:03:50           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-03         ┆ SoHo         ┆ Macchiato   ┆ Oat       ┆ 12   ┆ true  ┆ Christopher ┆ 2.9   │
│ 05:30:19           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-04         ┆ Uptown       ┆ Espresso    ┆ Soy       ┆ 20   ┆ false ┆ Joshua      ┆ 2.76  │
│ 18:46:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-05         ┆ Downtown     ┆ Macchiato   ┆ 2%        ┆ 12   ┆ false ┆ Robert      ┆ 5.49  │
│ 18:41:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Downtown     ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Jeffrey     ┆ 2.8   │
│ 07:47:07           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Downtown     ┆ Macchiato   ┆ Whole     ┆ 12   ┆ false ┆ Robert      ┆ 6.26  │
│ 21:39:23           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 6.49  │
│ 10:21:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

### Further Reading
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.or_.html

## Operator Precedence
- Polars prioritizes the AND (`&`) operator over the OR (`|`) operator.

In [90]:
is_almond_milk = pl.col("milk_type").eq("Almond")
is_iced = pl.col("iced")
is_cheap = pl.col("price").le(4)

coffees.filter(is_almond_milk | is_iced & is_cheap)

shape: (322, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.85  │
│ 07:52:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Joshua      ┆ 2.6   │
│ 01:50:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Macchiato   ┆ Coconut   ┆ 16   ┆ true  ┆ Joshua      ┆ 3.89  │
│ 12:27:29           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-03         ┆ SoHo         ┆ Macchiato   ┆ Oat       ┆ 12   ┆ true  ┆ Christopher ┆ 2.9   │
│ 05:30:19           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-06         ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true  ┆ Danielle    ┆ 3.33  │
│ 22:28:52           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ Midtown West ┆ Espresso    ┆ Almond    ┆ 12   ┆ true  ┆ Joshua      ┆ 4.54  │
│ 04:13:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle    ┆ 5.17  │
│ 06:12:20           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- Let's start by defining some Boolean expressions.

In [91]:
coffees.filter(is_almond_milk | (is_iced & is_cheap))

shape: (322, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.85  │
│ 07:52:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Joshua      ┆ 2.6   │
│ 01:50:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Macchiato   ┆ Coconut   ┆ 16   ┆ true  ┆ Joshua      ┆ 3.89  │
│ 12:27:29           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-03         ┆ SoHo         ┆ Macchiato   ┆ Oat       ┆ 12   ┆ true  ┆ Christopher ┆ 2.9   │
│ 05:30:19           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-06         ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true  ┆ Danielle    ┆ 3.33  │
│ 22:28:52           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ Midtown West ┆ Espresso    ┆ Almond    ┆ 12   ┆ true  ┆ Joshua      ┆ 4.54  │
│ 04:13:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle    ┆ 5.17  │
│ 06:12:20           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- How does Polars interpret the filter below?
- Option A ❌: Extract rows that are (almond milk OR iced) AND cheap
- Option B ✅: Extract rows that are almond milk OR (iced AND cheap)
- The `&` wins out so Polars group `is_iced & is_cheap` together.

In [92]:
coffees.filter((is_almond_milk | is_iced) & is_cheap)

shape: (202, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Joshua      ┆ 2.6   │
│ 01:50:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Macchiato   ┆ Coconut   ┆ 16   ┆ true  ┆ Joshua      ┆ 3.89  │
│ 12:27:29           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-03         ┆ SoHo         ┆ Macchiato   ┆ Oat       ┆ 12   ┆ true  ┆ Christopher ┆ 2.9   │
│ 05:30:19           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-03         ┆ Midtown West ┆ Flat White  ┆ Soy       ┆ 12   ┆ true  ┆ Anthony     ┆ 3.69  │
│ 10:57:47           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-04         ┆ Downtown     ┆ Espresso    ┆ Coconut   ┆ 20   ┆ true  ┆ Joshua      ┆ 2.98  │
│ 14:11:55           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-04         ┆ East Village ┆ Macchiato   ┆ Coconut   ┆ 12   ┆ true  ┆ Christopher ┆ 2.86  │
│ 14:41:15           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true  ┆ Danielle    ┆ 3.33  │
│ 22:28:52           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- Use parentheses to group together the related expressions.
- Use parentheses even if Polars' default inference is correct.

- The placement of parentheses switches up the result.
- The next example extracts rows that are (Almond milk OR Iced) AND cheap

## Exclusive OR
- The exclusive OR operator (`^`) requires that only one condition be met.
- If one condition is true, the other condition must be false.
- if both conditions are true, the `^` expression evaluates to false.
- The method equivalent is `xor`.

In [99]:
uptown = pl.col("location") == "Uptown"
oat_milk = pl.col("milk_type") == "Oat"

coffees.filter(uptown | oat_milk)

shape: (302, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true  ┆ Christopher ┆ 4.29  │
│ 02:39:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Danielle    ┆ 3.74  │
│ 15:07:27           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Joshua      ┆ 2.6   │
│ 01:50:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Macchiato   ┆ Coconut   ┆ 16   ┆ true  ┆ Joshua      ┆ 3.89  │
│ 12:27:29           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Americano   ┆ Coconut   ┆ 20   ┆ false ┆ Anthony     ┆ 4.08  │
│ 23:18:27           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-06         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 3.47  │
│ 14:36:47           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ East Village ┆ Flat White  ┆ Oat       ┆ 20   ┆ false ┆ Erica       ┆ 4.75  │
│ 14:51:19           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true  ┆ Danielle    ┆ 3.33  │
│ 22:28:52           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 6.49  │
│ 10:21:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- Let's filter for the rows with either a location of "Uptown" or a milk of "Oat".
- Polars will _exclude_ a row if it has both a location of "Uptown" and a milk of "Oat".

In [102]:
coffees.filter(uptown ^ oat_milk)
coffees.filter(uptown.xor(oat_milk))

shape: (270, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Danielle    ┆ 3.74  │
│ 15:07:27           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Macchiato   ┆ Coconut   ┆ 16   ┆ true  ┆ Joshua      ┆ 3.89  │
│ 12:27:29           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Americano   ┆ Coconut   ┆ 20   ┆ false ┆ Anthony     ┆ 4.08  │
│ 23:18:27           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-03         ┆ SoHo         ┆ Macchiato   ┆ Oat       ┆ 12   ┆ true  ┆ Christopher ┆ 2.9   │
│ 05:30:19           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-04         ┆ Uptown       ┆ Espresso    ┆ Soy       ┆ 20   ┆ false ┆ Joshua      ┆ 2.76  │
│ 18:46:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-06         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 3.47  │
│ 14:36:47           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ East Village ┆ Flat White  ┆ Oat       ┆ 20   ┆ false ┆ Erica       ┆ 4.75  │
│ 14:51:19           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true  ┆ Danielle    ┆ 3.33  │
│ 22:28:52           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 6.49  │
│ 10:21:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

### Further Reading
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.xor.html

## Filtering for Unique and Duplicate Values

- The `is_unique` method identifies if a row value is unique (only occurs once in the column).
- The `is_duplicated` method identifies if a row value is a duplicate. First occurrences count as duplicates.

In [104]:
coffees.filter(pl.col("coffee_name").is_unique())

shape: (4, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-27         ┆ SoHo         ┆ Frappe      ┆ Soy       ┆ 16   ┆ true  ┆ Jeffrey     ┆ 4.3   │
│ 01:50:31           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-02-07         ┆ East Village ┆ Affogato    ┆ 2%        ┆ 16   ┆ false ┆ Christopher ┆ 2.98  │
│ 09:30:28           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-04-15         ┆ Uptown       ┆ Red eye     ┆ 2%        ┆ 12   ┆ false ┆ Anthony     ┆ 4.71  │
│ 13:22:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-04-26         ┆ Midtown West ┆ Cortado     ┆ Whole     ┆ 20   ┆ true  ┆ Joshua      ┆ 5.58  │
│ 01:07:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

In [105]:
coffees.select(pl.col("coffee_name").value_counts(sort=True))

shape: (12, 1)
┌────────────────────┐
│ coffee_name        │
│ ---                │
│ struct[2]          │
╞════════════════════╡
│ {"Flat White",155} │
│ {"Macchiato",152}  │
│ {"Espresso",151}   │
│ {"Latte",139}      │
│ {"Mocha",134}      │
│ …                  │
│ {null,6}           │
│ {"Frappe",1}       │
│ {"Affogato",1}     │
│ {"Red eye",1}      │
│ {"Cortado",1}      │
└────────────────────┘

In [112]:
coffees.filter(pl.col("coffee_name").is_duplicated())

shape: (996, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true  ┆ Christopher ┆ 4.29  │
│ 02:39:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.85  │
│ 07:52:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ null        ┆ Soy       ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.05  │
│ 10:02:41           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Danielle    ┆ 3.74  │
│ 15:07:27           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-07         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 6.49  │
│ 10:21:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel       ┆ 4.82  │
│ 10:28:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle    ┆ 5.17  │
│ 06:12:20           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- The `is_first_distinct` method identifies if a row holds the first occurrence of a value, regardless of whether it is a duplicate or not.
- The `is_last_distinct` method identifies if a row holds the last occurrence of a value, regardless of whether it is a duplicate or not.

In [113]:
coffees.filter(pl.col("coffee_name").is_first_distinct())

shape: (12, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true  ┆ Christopher ┆ 4.29  │
│ 02:39:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.85  │
│ 07:52:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ null        ┆ Soy       ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.05  │
│ 10:02:41           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.83  │
│ 16:31:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-01-05         ┆ Downtown     ┆ Cappuccino  ┆ Oat       ┆ 12   ┆ false ┆ Erica       ┆ 3.71  │
│ 14:17:03           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-27         ┆ SoHo         ┆ Frappe      ┆ Soy       ┆ 16   ┆ true  ┆ Jeffrey     ┆ 4.3   │
│ 01:50:31           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-02-07         ┆ East Village ┆ Affogato    ┆ 2%        ┆ 16   ┆ false ┆ Christopher ┆ 2.98  │
│ 09:30:28           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-04-15         ┆ Uptown       ┆ Red eye     ┆ 2%        ┆ 12   ┆ false ┆ Anthony     ┆ 4.71  │
│ 13:22:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-04-26         ┆ Midtown West ┆ Cortado     ┆ Whole     ┆ 20   ┆ true  ┆ Joshua      ┆ 5.58  │
│ 01:07:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

In [114]:
coffees.filter(pl.col("coffee_name").is_last_distinct())

shape: (12, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-27         ┆ SoHo         ┆ Frappe      ┆ Soy       ┆ 16   ┆ true  ┆ Jeffrey     ┆ 4.3   │
│ 01:50:31           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-02-07         ┆ East Village ┆ Affogato    ┆ 2%        ┆ 16   ┆ false ┆ Christopher ┆ 2.98  │
│ 09:30:28           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-04-15         ┆ Uptown       ┆ Red eye     ┆ 2%        ┆ 12   ┆ false ┆ Anthony     ┆ 4.71  │
│ 13:22:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-04-26         ┆ Midtown West ┆ Cortado     ┆ Whole     ┆ 20   ┆ true  ┆ Joshua      ┆ 5.58  │
│ 01:07:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-05-10         ┆ SoHo         ┆ null        ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.4   │
│ 16:28:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-06         ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true  ┆ Danielle    ┆ 3.33  │
│ 22:28:52           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 6.49  │
│ 10:21:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel       ┆ 4.82  │
│ 10:28:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

### Further Reading
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.is_unique.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.is_duplicated.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.is_first_distinct.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.is_last_distinct.html

## Filtering with Datetimes
- The `filter` method supports filtering date, time, and datetime columns.

In [124]:
import datetime as dt

dt.date(2025, 6, 1)

coffees.filter(pl.col("time_of_purchase") >= dt.date(2025, 6, 1))
coffees.filter(pl.col("time_of_purchase").gt(dt.date(2025, 6, 1)))

shape: (47, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬──────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista  ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---      ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str      ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪══════════╪═══════╡
│ 2025-06-01 00:13:38 ┆ Midtown West ┆ Mocha       ┆ 2%        ┆ 12   ┆ false ┆ Patricia ┆ 3.03  │
│ 2025-06-01 00:46:22 ┆ SoHo         ┆ Macchiato   ┆ Oat       ┆ 12   ┆ false ┆ Danielle ┆ 3.67  │
│ 2025-06-01 03:42:07 ┆ Midtown West ┆ Flat White  ┆ Oat       ┆ 16   ┆ false ┆ Erica    ┆ 6.21  │
│ 2025-06-01 04:39:44 ┆ Downtown     ┆ Mocha       ┆ Oat       ┆ 20   ┆ false ┆ Erica    ┆ 5.66  │
│ 2025-06-01 11:36:18 ┆ Midtown West ┆ Cappuccino  ┆ Whole     ┆ 12   ┆ true  ┆ Angel    ┆ 4.51  │
│ …                   ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …        ┆ …     │
│ 2025-06-07 10:21:56 ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle ┆ 6.49  │
│ 2025-06-07 10:28:12 ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel    ┆ 4.82  │
│ 2025-06-08 06:12:20 ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle ┆ 5.17  │
│ 2025-06-08 10:56:38 ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle ┆ 2.87  │
│ 2025-06-08 13:34:09 ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua   ┆ 3.45  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴──────────┴───────┘

In [125]:
coffees.filter(pl.col("time_of_purchase") >= pl.date(2025, 6, 1))

shape: (47, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬──────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista  ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---      ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str      ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪══════════╪═══════╡
│ 2025-06-01 00:13:38 ┆ Midtown West ┆ Mocha       ┆ 2%        ┆ 12   ┆ false ┆ Patricia ┆ 3.03  │
│ 2025-06-01 00:46:22 ┆ SoHo         ┆ Macchiato   ┆ Oat       ┆ 12   ┆ false ┆ Danielle ┆ 3.67  │
│ 2025-06-01 03:42:07 ┆ Midtown West ┆ Flat White  ┆ Oat       ┆ 16   ┆ false ┆ Erica    ┆ 6.21  │
│ 2025-06-01 04:39:44 ┆ Downtown     ┆ Mocha       ┆ Oat       ┆ 20   ┆ false ┆ Erica    ┆ 5.66  │
│ 2025-06-01 11:36:18 ┆ Midtown West ┆ Cappuccino  ┆ Whole     ┆ 12   ┆ true  ┆ Angel    ┆ 4.51  │
│ …                   ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …        ┆ …     │
│ 2025-06-07 10:21:56 ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle ┆ 6.49  │
│ 2025-06-07 10:28:12 ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel    ┆ 4.82  │
│ 2025-06-08 06:12:20 ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle ┆ 5.17  │
│ 2025-06-08 10:56:38 ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle ┆ 2.87  │
│ 2025-06-08 13:34:09 ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua   ┆ 3.45  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴──────────┴───────┘

In [126]:
type(pl.date(2025, 6, 1))

polars.expr.expr.Expr

- Let's find all the coffees purchased on or after June 1st, 2025.
- Polars is less flexible than Pandas. It will not allow comparison of dates with time strings.

- To filter datetimes, we need to provide a valid date/datetime object from Python or Polars.
- Polars has a `date` function which has the same API as `dt.date` (year, month, and day).
- The `date` function returns an expression representing a date in time.
- `pl.date` is different from `pl.Date` which is the `Date` type.
- When using a date on a datetime column, Polars assumes a time of midnight (00:00:00).

- The `dt.datetime` constructor accepts the hours, minutes, and seconds after the year, month, and day.
- Here, we filter for the coffees purchased after June 1st, 2025 12:30:45pm.
- Polars has a complementary `pl.datetime` constructor.

In [127]:
coffees.filter(pl.col("time_of_purchase") >= pl.datetime(2025, 6, 1, 1, 1, 1))

shape: (45, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬──────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista  ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---      ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str      ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪══════════╪═══════╡
│ 2025-06-01 03:42:07 ┆ Midtown West ┆ Flat White  ┆ Oat       ┆ 16   ┆ false ┆ Erica    ┆ 6.21  │
│ 2025-06-01 04:39:44 ┆ Downtown     ┆ Mocha       ┆ Oat       ┆ 20   ┆ false ┆ Erica    ┆ 5.66  │
│ 2025-06-01 11:36:18 ┆ Midtown West ┆ Cappuccino  ┆ Whole     ┆ 12   ┆ true  ┆ Angel    ┆ 4.51  │
│ 2025-06-01 16:48:35 ┆ SoHo         ┆ Cappuccino  ┆ Almond    ┆ 20   ┆ false ┆ Anthony  ┆ 4.68  │
│ 2025-06-01 22:11:07 ┆ Downtown     ┆ Macchiato   ┆ Whole     ┆ 16   ┆ false ┆ Joshua   ┆ 2.86  │
│ …                   ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …        ┆ …     │
│ 2025-06-07 10:21:56 ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle ┆ 6.49  │
│ 2025-06-07 10:28:12 ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel    ┆ 4.82  │
│ 2025-06-08 06:12:20 ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle ┆ 5.17  │
│ 2025-06-08 10:56:38 ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle ┆ 2.87  │
│ 2025-06-08 13:34:09 ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua   ┆ 3.45  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴──────────┴───────┘

### Further Reading
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.date.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.datetime.html

## The is_between Method

- Let's say that we're targeting all transactions with a price between 3 and 4 dollars.
- When checking for inclusion in a range, one option is to declare each bound as a separate condition.

- The `is_between` method returns a Boolean expression that indicates whether a row value falls within a range.
- Both the lower bound and upper bound are inclusive.

### Further Reading
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.is_between.html

## The is_in Method
- The `is_in` method validates the inclusion of a row value within a collection of values.

- Say we want to extract rows where the `coffee_name` is either "Americano" or "Espresso".
- We can apply the `|` operator or the `_or` method to check for multiple independent expressions.

- The `is_in` method accepts a collection (list, tuple, etc) or another expression.

### Further Reading
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.is_in.html

## The remove Method
- The `filter` method includes rows that satisfy an expression.
- The `remove` method _excludes_ rows that satisfy an expression.
- The `remove` method performs the inverse logic of the `filter` method.

- Say we want to extract any rows where the `size` value is not equal to 12.

- Alternatively, we could `remove` any rows where the `size` value is equal to 12.

- We can validate the equality of `DataFrames` with the `equals` method.
- The `equals` method returns `True` if two `DataFrames` are equal (same columns, rows, values, etc).

- If you use `&` or provide multiple arguments, Polars will confirm both conditions are met to exclude a row.
- Polars will remove rows where the `size` is 12 and the `barista` is either "Christopher" or "Erica".
- Polars will keep rows with a size of 12 and a barista who is not Christopher or Erica.
- Polars will keep rows with a barista of Christopher or Erica and a size not equal to 12.

### Further Reading
- https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.remove.html

## Negation with the Tilde Symbol
- The tilde symbol (`~`) inverts a Boolean expression's values.
- A true becomes a false, and a false becomes a true.
- The method equivalent is `not_`. Python has a reserved `not` keyword.

- Let's extract the rows with coffee prices less than `$3` and greater than `$4`.

- Alternatively, we can target all rows with prices that don't fall between `$3` and `$4`.

- Use variables to provide context for what an expression represents.

### Further Reading
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.not_.html

## When, Then, Otherwise
- The `when` method creates a conditional expression.
- The `then` method assigns a value based on the condition being met.
- The `otherwise` method provides an optional fallback value if the condition is not met.

- Say we wanted to provide a description of every coffee based on the milk type.
- If the milk is "Oat", the description should be `"Creamy"`. Otherwise, fallback to `"Unknown"`.
- The `pl.lit` function returns an expression that represents a literal (i.e., fixed, constant) value.
- Without a fallback, Polars falls back to a missing value (`null`) for any non-matching value.

- Use the `otherwise` method to provide a fallback to use instead of `null`.

- We can chain multiple invocations of the `when` method in sequence.
- Each `when` method call creates a separate condition to match.
- The design is similar to a `switch case` statement in various programming languages.

### Further Reading
- https://docs.pola.rs/user-guide/expressions/basic-operations/#conditionals
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.when.html

## Partitioning DataFrames
- Say we wanted to extract a `DataFrame` for every unique coffee (`"Flat White"`, `"Latte"`).

- Use the `unique` method to return a column of unique values from a target column.
- Writing 12 `filter` statements is verbose and not future-proof.

- The `partition_by` method uses a column's unique values to return a list of `DataFrames`.
- The `partition_by` method accepts a string with the column's name (an expression is invalid).
- The word __partition__ means to "divide into parts".
- If we have 12 different coffees, then `partition_by` will return a list of 12 `DataFrames`.

- The list isn't particularly helpful because the `DataFrames` are accessible by index position.
- Polars will store the `DataFrames` in the order that it encounters the unique values in the original `DataFrame`.
- In this example, "Flat White" comes first, then "Latte", then "Macchiato", etc.
- The `as_dict` parameter returns a dictionary where the keys are tuples with the unique column values and the values are the `DataFrames`.

- Use square brackets to index into the dictionary and provide a tuple key to access the corresponding `DataFrame`.
- A tuple only requires a comma but is usually written in parentheses.

- The reason that the dictionary stores tuple keys is to support multi-key partitioning.
- Let's instead the split the `DataFrame` by every combination of coffee and milk.

- Pass a tuple with both the coffee and milk entry to extract the target `DataFrame`.
- A single value (i.e., "Americano") will trigger an error.

### Further Reading
- https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.partition_by.html