# Working with Text Data

In [15]:
import polars as pl

## NOTE: The NYC Dataset

The `nyc.csv` file is pretty large (500+ MB) so I've compressed it as a `.zip` archive in this folder. 

You'll need to unpack the CSV file in order for the following code samples to work.

- On macOS, double-click the `nyc.csv.zip` file.
- On Windows, right-click the `nyc.csv.zip` file and click `Extract All`. Extract the file to this folder.

- The `nyc.csv` dataset is a collection of public sector employees in New York City.

In [16]:
nyc = pl.read_csv("nyc.csv")
nyc.head()

shape: (5, 8)
┌──────────────┬───────────┬────────────┬──────────┬──────────┬──────────────┬─────────┬───────────┐
│ Agency Name  ┆ Last Name ┆ First Name ┆ Mid Init ┆ Borough  ┆ Title        ┆ Base    ┆ Pay Basis │
│ ---          ┆ ---       ┆ ---        ┆ ---      ┆ ---      ┆ ---          ┆ Salary  ┆ ---       │
│ str          ┆ str       ┆ str        ┆ str      ┆ str      ┆ str          ┆ ---     ┆ str       │
│              ┆           ┆            ┆          ┆          ┆              ┆ f64     ┆           │
╞══════════════╪═══════════╪════════════╪══════════╪══════════╪══════════════╪═════════╪═══════════╡
│ OFFICE OF    ┆ BEREZIN   ┆ MIKHAIL    ┆ null     ┆ BROOKLYN ┆ EMERGENCY    ┆ 86005.0 ┆ per Annum │
│ EMERGENCY    ┆           ┆            ┆          ┆          ┆ PREPAREDNESS ┆         ┆           │
│ MANAGEMEN…   ┆           ┆            ┆          ┆          ┆ MANAGER      ┆         ┆           │
│ OFFICE OF    ┆ GEAGER    ┆ VERONICA   ┆ M        ┆ BROOKLYN ┆ EMERGENCY    ┆ 86005.0 ┆ per Annum │
│ EMERGENCY    ┆           ┆            ┆          ┆          ┆ PREPAREDNESS ┆         ┆           │
│ MANAGEMENT…  ┆           ┆            ┆          ┆          ┆ MANAGER      ┆         ┆           │
│ OFFICE OF    ┆ RAMANI    ┆ SHRADDHA   ┆ null     ┆ BROOKLYN ┆ EMERGENCY    ┆ 86005.0 ┆ per Annum │
│ EMERGENCY    ┆           ┆            ┆          ┆          ┆ PREPAREDNESS ┆         ┆           │
│ MANAGEME…    ┆           ┆            ┆          ┆          ┆ MANAGER      ┆         ┆           │
│ OFFICE OF    ┆ ROTTA     ┆ JONATHAN   ┆ D        ┆ BROOKLYN ┆ EMERGENCY    ┆ 86005.0 ┆ per Annum │
│ EMERGENCY    ┆           ┆            ┆          ┆          ┆ PREPAREDNESS ┆         ┆           │
│ MANAGEMENT   ┆           ┆            ┆          ┆          ┆ MANAGER      ┆         ┆           │
│ OFFICE OF    ┆ WILSON II ┆ ROBERT     ┆ P        ┆ BROOKLYN ┆ EMERGENCY    ┆ 86005.0 ┆ per Annum │
│ EMERGENCY    ┆           ┆            ┆          ┆          ┆ PREPAREDNESS ┆         ┆           │
│ MANAGEMENT   ┆           ┆            ┆          ┆          ┆ MANAGER      ┆         ┆           │
└──────────────┴───────────┴────────────┴──────────┴──────────┴──────────────┴─────────┴───────────┘

- Let's see the count of null values and the count of present values.
- The `shape` attribute retuns the dimensions (height, width) of the `DataFrame`.
- The `count` method returns the number of present values per column.
- The `null_count` method returns the number of absent (`null`) values per column.

In [17]:
nyc.shape

(6225611, 8)

In [18]:
nyc.count()

shape: (1, 8)
┌─────────────┬───────────┬────────────┬──────────┬─────────┬─────────┬─────────────┬───────────┐
│ Agency Name ┆ Last Name ┆ First Name ┆ Mid Init ┆ Borough ┆ Title   ┆ Base Salary ┆ Pay Basis │
│ ---         ┆ ---       ┆ ---        ┆ ---      ┆ ---     ┆ ---     ┆ ---         ┆ ---       │
│ u32         ┆ u32       ┆ u32        ┆ u32      ┆ u32     ┆ u32     ┆ u32         ┆ u32       │
╞═════════════╪═══════════╪════════════╪══════════╪═════════╪═════════╪═════════════╪═══════════╡
│ 6225611     ┆ 6212030   ┆ 6212028    ┆ 3665572  ┆ 5719377 ┆ 6225447 ┆ 6225611     ┆ 6225611   │
└─────────────┴───────────┴────────────┴──────────┴─────────┴─────────┴─────────────┴───────────┘

In [19]:
nyc.null_count()

shape: (1, 8)
┌─────────────┬───────────┬────────────┬──────────┬─────────┬───────┬─────────────┬───────────┐
│ Agency Name ┆ Last Name ┆ First Name ┆ Mid Init ┆ Borough ┆ Title ┆ Base Salary ┆ Pay Basis │
│ ---         ┆ ---       ┆ ---        ┆ ---      ┆ ---     ┆ ---   ┆ ---         ┆ ---       │
│ u32         ┆ u32       ┆ u32        ┆ u32      ┆ u32     ┆ u32   ┆ u32         ┆ u32       │
╞═════════════╪═══════════╪════════════╪══════════╪═════════╪═══════╪═════════════╪═══════════╡
│ 0           ┆ 13581     ┆ 13583      ┆ 2560039  ┆ 506234  ┆ 164   ┆ 0           ┆ 0         │
└─────────────┴───────────┴────────────┴──────────┴─────────┴───────┴─────────────┴───────────┘

### Further Reading
- https://docs.pola.rs/api/python/stable/reference/api/polars.read_csv.html
- https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.shape.html
- https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.count.html
- https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.null_count.html

## Case Conversion
- Polars groups related methods under an attribute/accessor (a namespace).
- String methods have a dedicated `str` namespace.

In [20]:
nyc.select(
    pl.col("Borough").str.to_lowercase(),
    pl.col("Pay Basis").str.to_uppercase(),
    pl.col("Agency Name").str.to_titlecase(),
)

shape: (6_225_611, 3)
┌───────────┬───────────┬─────────────────────────────────┐
│ Borough   ┆ Pay Basis ┆ Agency Name                     │
│ ---       ┆ ---       ┆ ---                             │
│ str       ┆ str       ┆ str                             │
╞═══════════╪═══════════╪═════════════════════════════════╡
│ brooklyn  ┆ PER ANNUM ┆  Office Of Emergency Managemen… │
│ brooklyn  ┆ PER ANNUM ┆ Office Of Emergency Management… │
│ brooklyn  ┆ PER ANNUM ┆   Office Of Emergency Manageme… │
│ brooklyn  ┆ PER ANNUM ┆ Office Of Emergency Management  │
│ brooklyn  ┆ PER ANNUM ┆ Office Of Emergency Management  │
│ …         ┆ …         ┆ …                               │
│ bronx     ┆ PER DAY   ┆ Nyc Housing Authority           │
│ manhattan ┆ PER DAY   ┆ Nyc Housing Authority           │
│ manhattan ┆ PER DAY   ┆ Nyc Housing Authority           │
│ manhattan ┆ PER ANNUM ┆ Nyc Housing Authority           │
│ manhattan ┆ PER ANNUM ┆ Nyc Housing Authority           │
└───────────┴───────────┴─────────────────────────────────┘

- The `str.to_lowercase` method converts all characters to lowercase.
- The `str.to_uppercase` method converts all characters to uppercase.
- The `str.to_titlecase` method converts all characters to titlecase (capital letter of every first word).

In [21]:
nyc.select(pl.col("Borough").str.to_uppercase())

shape: (6_225_611, 1)
┌───────────┐
│ Borough   │
│ ---       │
│ str       │
╞═══════════╡
│ BROOKLYN  │
│ BROOKLYN  │
│ BROOKLYN  │
│ BROOKLYN  │
│ BROOKLYN  │
│ …         │
│ BRONX     │
│ MANHATTAN │
│ MANHATTAN │
│ MANHATTAN │
│ MANHATTAN │
└───────────┘

In [22]:
nyc.with_columns(pl.col(pl.String).str.to_titlecase())

shape: (6_225_611, 8)
┌────────────┬───────────┬────────────┬──────────┬───────────┬────────────┬────────────┬───────────┐
│ Agency     ┆ Last Name ┆ First Name ┆ Mid Init ┆ Borough   ┆ Title      ┆ Base       ┆ Pay Basis │
│ Name       ┆ ---       ┆ ---        ┆ ---      ┆ ---       ┆ ---        ┆ Salary     ┆ ---       │
│ ---        ┆ str       ┆ str        ┆ str      ┆ str       ┆ str        ┆ ---        ┆ str       │
│ str        ┆           ┆            ┆          ┆           ┆            ┆ f64        ┆           │
╞════════════╪═══════════╪════════════╪══════════╪═══════════╪════════════╪════════════╪═══════════╡
│ Office Of  ┆ Berezin   ┆ Mikhail    ┆ null     ┆ Brooklyn  ┆ Emergency  ┆ 86005.0    ┆ Per Annum │
│ Emergency  ┆           ┆            ┆          ┆           ┆ Preparedne ┆            ┆           │
│ Managemen… ┆           ┆            ┆          ┆           ┆ ss Manager ┆            ┆           │
│ Office Of  ┆ Geager    ┆ Veronica   ┆ M        ┆ Brooklyn  ┆ Emergency  ┆ 86005.0    ┆ Per Annum │
│ Emergency  ┆           ┆            ┆          ┆           ┆ Preparedne ┆            ┆           │
│ Management ┆           ┆            ┆          ┆           ┆ ss Manager ┆            ┆           │
│ …          ┆           ┆            ┆          ┆           ┆            ┆            ┆           │
│ Office Of  ┆ Ramani    ┆ Shraddha   ┆ null     ┆ Brooklyn  ┆ Emergency  ┆ 86005.0    ┆ Per Annum │
│ Emergency  ┆           ┆            ┆          ┆           ┆ Preparedne ┆            ┆           │
│ Manageme…  ┆           ┆            ┆          ┆           ┆ ss Manager ┆            ┆           │
│ Office Of  ┆ Rotta     ┆ Jonathan   ┆ D        ┆ Brooklyn  ┆ Emergency  ┆ 86005.0    ┆ Per Annum │
│ Emergency  ┆           ┆            ┆          ┆           ┆ Preparedne ┆            ┆           │
│ Management ┆           ┆            ┆          ┆           ┆ ss Manager ┆            ┆           │
│ Office Of  ┆ Wilson Ii ┆ Robert     ┆ P        ┆ Brooklyn  ┆ Emergency  ┆ 86005.0    ┆ Per Annum │
│ Emergency  ┆           ┆            ┆          ┆           ┆ Preparedne ┆            ┆           │
│ Management ┆           ┆            ┆          ┆           ┆ ss Manager ┆            ┆           │
│ …          ┆ …         ┆ …          ┆ …        ┆ …         ┆ …          ┆ …          ┆ …         │
│ Nyc        ┆ Daley     ┆ Garfield   ┆ D        ┆ Bronx     ┆ Supervisor ┆ 488.25     ┆ Per Day   │
│ Housing    ┆           ┆            ┆          ┆           ┆ Electricia ┆            ┆           │
│ Authority  ┆           ┆            ┆          ┆           ┆ n          ┆            ┆           │
│ Nyc        ┆ Duncan    ┆ Alvin      ┆ A        ┆ Manhattan ┆ Supervisor ┆ 548.0      ┆ Per Day   │
│ Housing    ┆           ┆            ┆          ┆           ┆ Elevator   ┆            ┆           │
│ Authority  ┆           ┆            ┆          ┆           ┆ Mechanic   ┆            ┆           │
│ Nyc        ┆ Romero    ┆ Vincent    ┆ null     ┆ Manhattan ┆ Supervisor ┆ 548.0      ┆ Per Day   │
│ Housing    ┆           ┆            ┆          ┆           ┆ Elevator   ┆            ┆           │
│ Authority  ┆           ┆            ┆          ┆           ┆ Mechanic   ┆            ┆           │
│ Nyc        ┆ Porcelli  ┆ Anthony    ┆ null     ┆ Manhattan ┆ Administra ┆ 163741.0   ┆ Per Annum │
│ Housing    ┆           ┆            ┆          ┆           ┆ tive       ┆            ┆           │
│ Authority  ┆           ┆            ┆          ┆           ┆ Housing    ┆            ┆           │
│            ┆           ┆            ┆          ┆           ┆ Superin…   ┆            ┆           │
│ Nyc        ┆ Colon     ┆ Sibyl      ┆ null     ┆ Manhattan ┆ Administra ┆ 135000.0   ┆ Per Annum │
│ Housing    ┆           ┆            ┆          ┆           ┆ tive       ┆            ┆           │
│ Authority  ┆           ┆            ┆          ┆           ┆ Housing    ┆            ┆           │
│            ┆           ┆            ┆          ┆           ┆ Manager    ┆            ┆           │
└────────────┴───────────┴────────────┴──────────┴───────────┴────────────┴────────────┴───────────┘

In [25]:
nyc.select(pl.col("Borough").str.to_titlecase())

shape: (6_225_611, 1)
┌───────────┐
│ Borough   │
│ ---       │
│ str       │
╞═══════════╡
│ Brooklyn  │
│ Brooklyn  │
│ Brooklyn  │
│ Brooklyn  │
│ Brooklyn  │
│ …         │
│ Bronx     │
│ Manhattan │
│ Manhattan │
│ Manhattan │
│ Manhattan │
└───────────┘

- Converting all the string columns to titlecase seems ideal for this dataset.
- We can pass a Polars data type to the `pl.col` function to target columns with that data type.
- `with_columns` will elegantly replace old columns with new ones (if they have the same name).

In [28]:
nyc.select(
    pl.col("Agency Name"),
    pl.col("Agency Name").str.strip_chars().alias("Agency Name without whitespace"),
)

shape: (6_225_611, 2)
┌─────────────────────────────────┬────────────────────────────────┐
│ Agency Name                     ┆ Agency Name without whitespace │
│ ---                             ┆ ---                            │
│ str                             ┆ str                            │
╞═════════════════════════════════╪════════════════════════════════╡
│  OFFICE OF EMERGENCY MANAGEMEN… ┆ OFFICE OF EMERGENCY MANAGEMENT │
│ OFFICE OF EMERGENCY MANAGEMENT… ┆ OFFICE OF EMERGENCY MANAGEMENT │
│   OFFICE OF EMERGENCY MANAGEME… ┆ OFFICE OF EMERGENCY MANAGEMENT │
│ OFFICE OF EMERGENCY MANAGEMENT  ┆ OFFICE OF EMERGENCY MANAGEMENT │
│ OFFICE OF EMERGENCY MANAGEMENT  ┆ OFFICE OF EMERGENCY MANAGEMENT │
│ …                               ┆ …                              │
│ NYC HOUSING AUTHORITY           ┆ NYC HOUSING AUTHORITY          │
│ NYC HOUSING AUTHORITY           ┆ NYC HOUSING AUTHORITY          │
│ NYC HOUSING AUTHORITY           ┆ NYC HOUSING AUTHORITY          │
│ NYC HOUSING AUTHORITY           ┆ NYC HOUSING AUTHORITY          │
│ NYC HOUSING AUTHORITY           ┆ NYC HOUSING AUTHORITY          │
└─────────────────────────────────┴────────────────────────────────┘

### Further Reading
- https://docs.pola.rs/user-guide/expressions/strings/#case-conversion
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.to_lowercase.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.to_uppercase.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.to_titlecase.html

## Removing Whitespace

- The `strip` method removes whitespace from the beginning and end of a string.
- The `lstrip` method removes whitespace from the beginning of a string.
- The `rstrip` method removes whitespace from the end of a string.

- The `str.strip_chars` method removes whitespace from the beginning and end of the string.
- The `str.strip_chars_start` method removes whitespace from the beginning of the string.
- The `str.strip_chars_end` method removes whitespace from the end of the string.

In [30]:
nyc.with_columns(
    pl.col(pl.String).str.strip_chars().str.to_titlecase(),
)

shape: (6_225_611, 8)
┌────────────┬───────────┬────────────┬──────────┬───────────┬────────────┬────────────┬───────────┐
│ Agency     ┆ Last Name ┆ First Name ┆ Mid Init ┆ Borough   ┆ Title      ┆ Base       ┆ Pay Basis │
│ Name       ┆ ---       ┆ ---        ┆ ---      ┆ ---       ┆ ---        ┆ Salary     ┆ ---       │
│ ---        ┆ str       ┆ str        ┆ str      ┆ str       ┆ str        ┆ ---        ┆ str       │
│ str        ┆           ┆            ┆          ┆           ┆            ┆ f64        ┆           │
╞════════════╪═══════════╪════════════╪══════════╪═══════════╪════════════╪════════════╪═══════════╡
│ Office Of  ┆ Berezin   ┆ Mikhail    ┆ null     ┆ Brooklyn  ┆ Emergency  ┆ 86005.0    ┆ Per Annum │
│ Emergency  ┆           ┆            ┆          ┆           ┆ Preparedne ┆            ┆           │
│ Management ┆           ┆            ┆          ┆           ┆ ss Manager ┆            ┆           │
│ Office Of  ┆ Geager    ┆ Veronica   ┆ M        ┆ Brooklyn  ┆ Emergency  ┆ 86005.0    ┆ Per Annum │
│ Emergency  ┆           ┆            ┆          ┆           ┆ Preparedne ┆            ┆           │
│ Management ┆           ┆            ┆          ┆           ┆ ss Manager ┆            ┆           │
│ Office Of  ┆ Ramani    ┆ Shraddha   ┆ null     ┆ Brooklyn  ┆ Emergency  ┆ 86005.0    ┆ Per Annum │
│ Emergency  ┆           ┆            ┆          ┆           ┆ Preparedne ┆            ┆           │
│ Management ┆           ┆            ┆          ┆           ┆ ss Manager ┆            ┆           │
│ Office Of  ┆ Rotta     ┆ Jonathan   ┆ D        ┆ Brooklyn  ┆ Emergency  ┆ 86005.0    ┆ Per Annum │
│ Emergency  ┆           ┆            ┆          ┆           ┆ Preparedne ┆            ┆           │
│ Management ┆           ┆            ┆          ┆           ┆ ss Manager ┆            ┆           │
│ Office Of  ┆ Wilson Ii ┆ Robert     ┆ P        ┆ Brooklyn  ┆ Emergency  ┆ 86005.0    ┆ Per Annum │
│ Emergency  ┆           ┆            ┆          ┆           ┆ Preparedne ┆            ┆           │
│ Management ┆           ┆            ┆          ┆           ┆ ss Manager ┆            ┆           │
│ …          ┆ …         ┆ …          ┆ …        ┆ …         ┆ …          ┆ …          ┆ …         │
│ Nyc        ┆ Daley     ┆ Garfield   ┆ D        ┆ Bronx     ┆ Supervisor ┆ 488.25     ┆ Per Day   │
│ Housing    ┆           ┆            ┆          ┆           ┆ Electricia ┆            ┆           │
│ Authority  ┆           ┆            ┆          ┆           ┆ n          ┆            ┆           │
│ Nyc        ┆ Duncan    ┆ Alvin      ┆ A        ┆ Manhattan ┆ Supervisor ┆ 548.0      ┆ Per Day   │
│ Housing    ┆           ┆            ┆          ┆           ┆ Elevator   ┆            ┆           │
│ Authority  ┆           ┆            ┆          ┆           ┆ Mechanic   ┆            ┆           │
│ Nyc        ┆ Romero    ┆ Vincent    ┆ null     ┆ Manhattan ┆ Supervisor ┆ 548.0      ┆ Per Day   │
│ Housing    ┆           ┆            ┆          ┆           ┆ Elevator   ┆            ┆           │
│ Authority  ┆           ┆            ┆          ┆           ┆ Mechanic   ┆            ┆           │
│ Nyc        ┆ Porcelli  ┆ Anthony    ┆ null     ┆ Manhattan ┆ Administra ┆ 163741.0   ┆ Per Annum │
│ Housing    ┆           ┆            ┆          ┆           ┆ tive       ┆            ┆           │
│ Authority  ┆           ┆            ┆          ┆           ┆ Housing    ┆            ┆           │
│            ┆           ┆            ┆          ┆           ┆ Superin…   ┆            ┆           │
│ Nyc        ┆ Colon     ┆ Sibyl      ┆ null     ┆ Manhattan ┆ Administra ┆ 135000.0   ┆ Per Annum │
│ Housing    ┆           ┆            ┆          ┆           ┆ tive       ┆            ┆           │
│ Authority  ┆           ┆            ┆          ┆           ┆ Housing    ┆            ┆           │
│            ┆           ┆            ┆          ┆           ┆ Manager    ┆            ┆           │
└────────────┴───────────┴────────────┴──────────┴───────────┴────────────┴────────────┴───────────┘

- We can method chain multiple string methods.
- Each method call requires the `str` attribute. The method is found _within_ the namespace.
- Let's first remove whitespace from all string columns, then titlecase their values.

### Further Reading
- https://docs.pola.rs/user-guide/expressions/strings/#stripping-characters-from-the-ends
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.strip_chars.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.strip_chars_start.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.strip_chars_end.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.to_titlecase.html

## Removing Prefix and Suffix

- The `str.strip_prefix` method removes a consistent substring from the beginning of each string.
- Polars will remove the prefix exactly once.
- For example, we can remove `Office Of ` from the start of every string that includes the text.

In [33]:
nyc.select(pl.col("Agency Name").str.strip_prefix("OFFICE OF "))

shape: (6_225_611, 1)
┌─────────────────────────────────┐
│ Agency Name                     │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│  OFFICE OF EMERGENCY MANAGEMEN… │
│ EMERGENCY MANAGEMENT            │
│   OFFICE OF EMERGENCY MANAGEME… │
│ EMERGENCY MANAGEMENT            │
│ EMERGENCY MANAGEMENT            │
│ …                               │
│ NYC HOUSING AUTHORITY           │
│ NYC HOUSING AUTHORITY           │
│ NYC HOUSING AUTHORITY           │
│ NYC HOUSING AUTHORITY           │
│ NYC HOUSING AUTHORITY           │
└─────────────────────────────────┘

- The complementary `str.strip_suffix` method removes a substring from the end of each string.

In [34]:
nyc.select(pl.col("Agency Name").str.strip_suffix("AUTHORITY"))

shape: (6_225_611, 1)
┌─────────────────────────────────┐
│ Agency Name                     │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│  OFFICE OF EMERGENCY MANAGEMEN… │
│ OFFICE OF EMERGENCY MANAGEMENT… │
│   OFFICE OF EMERGENCY MANAGEME… │
│ OFFICE OF EMERGENCY MANAGEMENT  │
│ OFFICE OF EMERGENCY MANAGEMENT  │
│ …                               │
│ NYC HOUSING                     │
│ NYC HOUSING                     │
│ NYC HOUSING                     │
│ NYC HOUSING                     │
│ NYC HOUSING                     │
└─────────────────────────────────┘

### Further Reading
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.strip_prefix.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.strip_suffix.html

## Characters vs. Bytes
- Every English character occupies 1 byte in memory. A string like "pizza" occupies 5 bytes in memory.
- Not all characters occupy one byte. Examples include non-English characters and emojis.
- For example, a 🍕 appears visually as 1 character but occupies 4 bytes in memory.
- To access the emoji keyboard, use `Fn + E` on macOS or `Windows + .` on Windows.

In [37]:
launches = pl.DataFrame({"person": ["Bobby", "Kelsey"], "launch": ["🍕", "🥩"]})

- The `str.len_bytes` method returns the number of bytes used to store each row value.
- The `str.len_chars` method returns a count of the string's characters.
- ASCII (American Standard Code for Information Exchange) text is a set of 128 characters that includes the whole English alphabet (lowercase and uppercase), the digits 0-9, and symbols (e.g., `?`, `!`, `.`, `$`).
- If you you are working with ASCII data, `len_bytes` will be faster.

In [44]:
launches.with_columns(
    pl.col("launch").str.len_bytes().alias("length in bytes"),
    pl.col("launch").str.len_chars().alias("length in chars"),
)

shape: (2, 4)
┌────────┬────────┬─────────────────┬─────────────────┐
│ person ┆ launch ┆ length in bytes ┆ length in chars │
│ ---    ┆ ---    ┆ ---             ┆ ---             │
│ str    ┆ str    ┆ u32             ┆ u32             │
╞════════╪════════╪═════════════════╪═════════════════╡
│ Bobby  ┆ 🍕     ┆ 4               ┆ 1               │
│ Kelsey ┆ 🥩     ┆ 4               ┆ 1               │
└────────┴────────┴─────────────────┴─────────────────┘

- The number of characters is not always equal to the number of bytes.
- An emoji appears as 1 visual character but may occupy multiple bytes in memory.

In [45]:
nyc.select(
    pl.col("Borough"),
    pl.col("Borough").str.slice(0, 3).alias("code"),
)

shape: (6_225_611, 2)
┌───────────┬──────┐
│ Borough   ┆ code │
│ ---       ┆ ---  │
│ str       ┆ str  │
╞═══════════╪══════╡
│ BROOKLYN  ┆ BRO  │
│ BROOKLYN  ┆ BRO  │
│ BROOKLYN  ┆ BRO  │
│ BROOKLYN  ┆ BRO  │
│ BROOKLYN  ┆ BRO  │
│ …         ┆ …    │
│ BRONX     ┆ BRO  │
│ MANHATTAN ┆ MAN  │
│ MANHATTAN ┆ MAN  │
│ MANHATTAN ┆ MAN  │
│ MANHATTAN ┆ MAN  │
└───────────┴──────┘

### Further Reading
- https://docs.pola.rs/user-guide/expressions/strings/#the-string-namespace
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.len_bytes.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.len_chars.html

## String Slicing

- The `str.slice` method extracts a sequence of characters from each string.
- The first argument is the starting index, and the second argument is the number of characters to slice.
- Let's assign each borough a 3-letter code based on its first 3 letters.

In [46]:
nyc.select(
    pl.col("Borough"),
    pl.col("Borough").str.slice(0, 100).alias("code"),
)

shape: (6_225_611, 2)
┌───────────┬───────────┐
│ Borough   ┆ code      │
│ ---       ┆ ---       │
│ str       ┆ str       │
╞═══════════╪═══════════╡
│ BROOKLYN  ┆ BROOKLYN  │
│ BROOKLYN  ┆ BROOKLYN  │
│ BROOKLYN  ┆ BROOKLYN  │
│ BROOKLYN  ┆ BROOKLYN  │
│ BROOKLYN  ┆ BROOKLYN  │
│ …         ┆ …         │
│ BRONX     ┆ BRONX     │
│ MANHATTAN ┆ MANHATTAN │
│ MANHATTAN ┆ MANHATTAN │
│ MANHATTAN ┆ MANHATTAN │
│ MANHATTAN ┆ MANHATTAN │
└───────────┴───────────┘

- If the slice extends past the end of the string, Polars will collect all the characters.

In [47]:
nyc.select(
    pl.col("Borough"),
    pl.col("Borough").str.slice(2, 5).alias("code"),
)

shape: (6_225_611, 2)
┌───────────┬───────┐
│ Borough   ┆ code  │
│ ---       ┆ ---   │
│ str       ┆ str   │
╞═══════════╪═══════╡
│ BROOKLYN  ┆ OOKLY │
│ BROOKLYN  ┆ OOKLY │
│ BROOKLYN  ┆ OOKLY │
│ BROOKLYN  ┆ OOKLY │
│ BROOKLYN  ┆ OOKLY │
│ …         ┆ …     │
│ BRONX     ┆ ONX   │
│ MANHATTAN ┆ NHATT │
│ MANHATTAN ┆ NHATT │
│ MANHATTAN ┆ NHATT │
│ MANHATTAN ┆ NHATT │
└───────────┴───────┘

- We can start in the middle of a string by specifying a non-zero index.

In [51]:
nyc.select(
    pl.col("Borough"),
    pl.col("Borough").str.head(3).alias("head_code"),
    pl.col("Borough").str.tail(3).alias("tail_code"),
)

shape: (6_225_611, 3)
┌───────────┬───────────┬───────────┐
│ Borough   ┆ head_code ┆ tail_code │
│ ---       ┆ ---       ┆ ---       │
│ str       ┆ str       ┆ str       │
╞═══════════╪═══════════╪═══════════╡
│ BROOKLYN  ┆ BRO       ┆ LYN       │
│ BROOKLYN  ┆ BRO       ┆ LYN       │
│ BROOKLYN  ┆ BRO       ┆ LYN       │
│ BROOKLYN  ┆ BRO       ┆ LYN       │
│ BROOKLYN  ┆ BRO       ┆ LYN       │
│ …         ┆ …         ┆ …         │
│ BRONX     ┆ BRO       ┆ ONX       │
│ MANHATTAN ┆ MAN       ┆ TAN       │
│ MANHATTAN ┆ MAN       ┆ TAN       │
│ MANHATTAN ┆ MAN       ┆ TAN       │
│ MANHATTAN ┆ MAN       ┆ TAN       │
└───────────┴───────────┴───────────┘

- The `str.head` method pulls characters from the beginning of the string.
- The `str.tail` method pulls characters at the end of the string.
- As with `str.slice`, if the requested amount extends past the string length, Polars will pull as many characters as possible.

### Further Reading
- https://docs.pola.rs/user-guide/expressions/strings/#slicing
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.slice.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.head.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.tail.html

## Filtering Methods

In [57]:
nyc.filter(pl.col("Title").str.to_lowercase().str.contains("water"))

shape: (4_202, 8)
┌────────────┬────────────┬────────────┬──────────┬──────────┬────────────┬────────────┬───────────┐
│ Agency     ┆ Last Name  ┆ First Name ┆ Mid Init ┆ Borough  ┆ Title      ┆ Base       ┆ Pay Basis │
│ Name       ┆ ---        ┆ ---        ┆ ---      ┆ ---      ┆ ---        ┆ Salary     ┆ ---       │
│ ---        ┆ str        ┆ str        ┆ str      ┆ str      ┆ str        ┆ ---        ┆ str       │
│ str        ┆            ┆            ┆          ┆          ┆            ┆ f64        ┆           │
╞════════════╪════════════╪════════════╪══════════╪══════════╪════════════╪════════════╪═══════════╡
│ DEPT OF    ┆ DELANEY    ┆ DENNIS     ┆ M        ┆ QUEENS   ┆ SUPERINTEN ┆ 170804.0   ┆ per Annum │
│ ENVIRONMEN ┆            ┆            ┆          ┆          ┆ DENT OF    ┆            ┆           │
│ T          ┆            ┆            ┆          ┆          ┆ WATER AND  ┆            ┆           │
│ PROTECTION ┆            ┆            ┆          ┆          ┆ SE…        ┆            ┆           │
│ DEPT OF    ┆ SHIRLEY    ┆ WINSTON    ┆ null     ┆ QUEENS   ┆ ASSOC      ┆ 164800.0   ┆ per Annum │
│ ENVIRONMEN ┆            ┆            ┆          ┆          ┆ WATER USE  ┆            ┆           │
│ T          ┆            ┆            ┆          ┆          ┆ INSPECTOR- ┆            ┆           │
│ PROTECTION ┆            ┆            ┆          ┆          ┆ MGRL       ┆            ┆           │
│ DEPT OF    ┆ MARCHESE   ┆ ANTHONY    ┆ null     ┆ QUEENS   ┆ SUPERINTEN ┆ 157960.0   ┆ per Annum │
│ ENVIRONMEN ┆            ┆            ┆          ┆          ┆ DENT OF    ┆            ┆           │
│ T          ┆            ┆            ┆          ┆          ┆ WATER AND  ┆            ┆           │
│ PROTECTION ┆            ┆            ┆          ┆          ┆ SE…        ┆            ┆           │
│ DEPT OF    ┆ VILLELLA   ┆ PAUL       ┆ null     ┆ QUEENS   ┆ SUPERINTEN ┆ 157960.0   ┆ per Annum │
│ ENVIRONMEN ┆            ┆            ┆          ┆          ┆ DENT OF    ┆            ┆           │
│ T          ┆            ┆            ┆          ┆          ┆ WATER AND  ┆            ┆           │
│ PROTECTION ┆            ┆            ┆          ┆          ┆ SE…        ┆            ┆           │
│ DEPT OF    ┆ CASTIGLION ┆ JOHN       ┆ A        ┆ QUEENS   ┆ SUPERINTEN ┆ 146260.0   ┆ per Annum │
│ ENVIRONMEN ┆ E          ┆            ┆          ┆          ┆ DENT OF    ┆            ┆           │
│ T          ┆            ┆            ┆          ┆          ┆ WATER AND  ┆            ┆           │
│ PROTECTION ┆            ┆            ┆          ┆          ┆ SE…        ┆            ┆           │
│ …          ┆ …          ┆ …          ┆ …        ┆ …        ┆ …          ┆ …          ┆ …         │
│ DEPT OF    ┆ OSTERHOUT  ┆ TIMOTHY    ┆ J        ┆ SULLIVAN ┆ WATERSHED  ┆ 67550.0    ┆ per Annum │
│ ENVIRONMEN ┆            ┆            ┆          ┆          ┆ MAINTAINER ┆            ┆           │
│ T          ┆            ┆            ┆          ┆          ┆            ┆            ┆           │
│ PROTECTION ┆            ┆            ┆          ┆          ┆            ┆            ┆           │
│ DEPT OF    ┆ DIPRESSI   ┆ SALVATORE  ┆ null     ┆ DUTCHESS ┆ WATERSHED  ┆ 67550.0    ┆ per Annum │
│ ENVIRONMEN ┆            ┆            ┆          ┆          ┆ MAINTAINER ┆            ┆           │
│ T          ┆            ┆            ┆          ┆          ┆            ┆            ┆           │
│ PROTECTION ┆            ┆            ┆          ┆          ┆            ┆            ┆           │
│ DEPT OF    ┆ VALENCHIS  ┆ LEO        ┆ A        ┆ ULSTER   ┆ WATERSHED  ┆ 61818.0    ┆ per Annum │
│ ENVIRONMEN ┆ SR         ┆            ┆          ┆          ┆ MAINTAINER ┆            ┆           │
│ T          ┆            ┆            ┆          ┆          ┆            ┆            ┆           │
│ PROTECTION ┆            ┆            ┆          ┆          ┆            ┆            ┆           │
│ DEPT OF    ┆ MCCOY      ┆ LONNIE     ┆ R        ┆ QUEENS   ┆ SUPERINTEN ┆ 90.18      ┆ per Hour  │
│ ENVIRONMEN ┆            ┆            ┆          ┆          ┆ DENT OF    ┆            ┆           │
│ T          ┆            ┆            ┆          ┆          ┆ WATER AND  ┆            ┆           │
│ PROTECTION ┆            ┆            ┆          ┆          ┆ SE…        ┆            ┆           │
│ DEPT OF    ┆ RIDER JR   ┆ STEPHEN    ┆ D        ┆ ULSTER   ┆ WATERSHED  ┆ 63673.0    ┆ per Annum │
│ ENVIRONMEN ┆            ┆            ┆          ┆          ┆ MAINTAINER ┆            ┆           │
│ T          ┆            ┆            ┆          ┆          ┆            ┆            ┆           │
│ PROTECTION ┆            ┆            ┆          ┆          ┆            ┆            ┆           │
└────────────┴────────────┴────────────┴──────────┴──────────┴────────────┴────────────┴───────────┘

- The `str.contains` method returns true if a row contains a given substring.

In [60]:
nyc.filter(pl.col("Title").str.to_lowercase().str.contains_any(["water", "fire"]))

shape: (112_163, 8)
┌────────────┬────────────┬────────────┬──────────┬───────────┬────────────┬───────────┬───────────┐
│ Agency     ┆ Last Name  ┆ First Name ┆ Mid Init ┆ Borough   ┆ Title      ┆ Base      ┆ Pay Basis │
│ Name       ┆ ---        ┆ ---        ┆ ---      ┆ ---       ┆ ---        ┆ Salary    ┆ ---       │
│ ---        ┆ str        ┆ str        ┆ str      ┆ str       ┆ str        ┆ ---       ┆ str       │
│ str        ┆            ┆            ┆          ┆           ┆            ┆ f64       ┆           │
╞════════════╪════════════╪════════════╪══════════╪═══════════╪════════════╪═══════════╪═══════════╡
│ FIRE       ┆ FLYNN      ┆ DANIEL     ┆ E        ┆ MANHATTAN ┆ SUPERVISIN ┆ 119596.0  ┆ per Annum │
│ DEPARTMENT ┆            ┆            ┆          ┆           ┆ G FIRE     ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ MARSHAL    ┆           ┆           │
│ FIRE       ┆ KANE       ┆ THOMAS     ┆ G        ┆ BROOKLYN  ┆ CHIEF FIRE ┆ 235462.0  ┆ per Annum │
│ DEPARTMENT ┆            ┆            ┆          ┆           ┆ MARSHAL    ┆           ┆           │
│ FIRE       ┆ PREZANT    ┆ DAVID      ┆ J        ┆ MANHATTAN ┆ FIRE       ┆ 232478.0  ┆ per Annum │
│ DEPARTMENT ┆            ┆            ┆          ┆           ┆ MEDICAL    ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ OFFICER    ┆           ┆           │
│ FIRE       ┆ DURKIN     ┆ MICHAEL    ┆ B        ┆ BROOKLYN  ┆ ASSISTANT  ┆ 215352.0  ┆ per Annum │
│ DEPARTMENT ┆            ┆            ┆          ┆           ┆ CHIEF FIRE ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ MARSHAL    ┆           ┆           │
│ FIRE       ┆ KREBS      ┆ BRIAN      ┆ M        ┆ QUEENS    ┆ SUPERVISIN ┆ 119596.0  ┆ per Annum │
│ DEPARTMENT ┆            ┆            ┆          ┆           ┆ G FIRE     ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ MARSHAL    ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …        ┆ …         ┆ …          ┆ …         ┆ …         │
│ NYC        ┆ YOK        ┆ RATHJERRY  ┆ null     ┆ MANHATTAN ┆ ASSOCIATE  ┆ 78733.0   ┆ per Annum │
│ HOUSING    ┆            ┆            ┆          ┆           ┆ FIRE       ┆           ┆           │
│ AUTHORITY  ┆            ┆            ┆          ┆           ┆ PROTECTION ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ INSP…      ┆           ┆           │
│ NYC        ┆ JEANFRANCO ┆ PIERRE     ┆ null     ┆ MANHATTAN ┆ ASSOCIATE  ┆ 74984.0   ┆ per Annum │
│ HOUSING    ┆ IS         ┆            ┆          ┆           ┆ FIRE       ┆           ┆           │
│ AUTHORITY  ┆            ┆            ┆          ┆           ┆ PROTECTION ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ INSP…      ┆           ┆           │
│ NYC        ┆ TERRANOVA  ┆ JOSEPH     ┆ null     ┆ QUEENS    ┆ ADMINISTRA ┆ 166112.0  ┆ per Annum │
│ HOUSING    ┆            ┆            ┆          ┆           ┆ TIVE FIRE  ┆           ┆           │
│ AUTHORITY  ┆            ┆            ┆          ┆           ┆ PROTECTION ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ …          ┆           ┆           │
│ NYC        ┆ CORTES     ┆ JOHNNY     ┆ S        ┆ MANHATTAN ┆ ADMINISTRA ┆ 143926.0  ┆ per Annum │
│ HOUSING    ┆            ┆            ┆          ┆           ┆ TIVE FIRE  ┆           ┆           │
│ AUTHORITY  ┆            ┆            ┆          ┆           ┆ PROTECTION ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ …          ┆           ┆           │
│ NYC        ┆ WILLIAMS   ┆ DONALD     ┆ R        ┆ MANHATTAN ┆ ASSOCIATE  ┆ 80340.0   ┆ per Annum │
│ HOUSING    ┆            ┆            ┆          ┆           ┆ FIRE       ┆           ┆           │
│ AUTHORITY  ┆            ┆            ┆          ┆           ┆ PROTECTION ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ INSP…      ┆           ┆           │
└────────────┴────────────┴────────────┴──────────┴───────────┴────────────┴───────────┴───────────┘

- The `str.contains_any` method returns true if the row value is found within a set of possible values.

In [62]:
nyc.filter(pl.col("Title").str.to_lowercase().str.starts_with("water"))

shape: (3_367, 8)
┌────────────┬────────────┬────────────┬──────────┬────────────┬───────────┬───────────┬───────────┐
│ Agency     ┆ Last Name  ┆ First Name ┆ Mid Init ┆ Borough    ┆ Title     ┆ Base      ┆ Pay Basis │
│ Name       ┆ ---        ┆ ---        ┆ ---      ┆ ---        ┆ ---       ┆ Salary    ┆ ---       │
│ ---        ┆ str        ┆ str        ┆ str      ┆ str        ┆ str       ┆ ---       ┆ str       │
│ str        ┆            ┆            ┆          ┆            ┆           ┆ f64       ┆           │
╞════════════╪════════════╪════════════╪══════════╪════════════╪═══════════╪═══════════╪═══════════╡
│ DEPT OF    ┆ DAVE       ┆ SALILKUMAR ┆ P        ┆ WESTCHESTE ┆ WATERSHED ┆ 60017.0   ┆ per Annum │
│ ENVIRONMEN ┆            ┆            ┆          ┆ R          ┆ MAINTAINE ┆           ┆           │
│ T          ┆            ┆            ┆          ┆            ┆ R         ┆           ┆           │
│ PROTECTION ┆            ┆            ┆          ┆            ┆           ┆           ┆           │
│ DEPT OF    ┆ SALDIVIA   ┆ VINCENT    ┆ E        ┆ WESTCHESTE ┆ WATERSHED ┆ 60017.0   ┆ per Annum │
│ ENVIRONMEN ┆            ┆            ┆          ┆ R          ┆ MAINTAINE ┆           ┆           │
│ T          ┆            ┆            ┆          ┆            ┆ R         ┆           ┆           │
│ PROTECTION ┆            ┆            ┆          ┆            ┆           ┆           ┆           │
│ DEPT OF    ┆ VARGHESE   ┆ SAM        ┆ M        ┆ WESTCHESTE ┆ WATERSHED ┆ 60017.0   ┆ per Annum │
│ ENVIRONMEN ┆            ┆            ┆          ┆ R          ┆ MAINTAINE ┆           ┆           │
│ T          ┆            ┆            ┆          ┆            ┆ R         ┆           ┆           │
│ PROTECTION ┆            ┆            ┆          ┆            ┆           ┆           ┆           │
│ DEPT OF    ┆ ALVAREZ    ┆ PAUL       ┆ D        ┆ WESTCHESTE ┆ WATERSHED ┆ 60655.0   ┆ per Annum │
│ ENVIRONMEN ┆            ┆            ┆          ┆ R          ┆ MAINTAINE ┆           ┆           │
│ T          ┆            ┆            ┆          ┆            ┆ R         ┆           ┆           │
│ PROTECTION ┆            ┆            ┆          ┆            ┆           ┆           ┆           │
│ DEPT OF    ┆ BOSGANG    ┆ EPHRAIM    ┆ A        ┆ WESTCHESTE ┆ WATERSHED ┆ 60146.0   ┆ per Annum │
│ ENVIRONMEN ┆            ┆            ┆          ┆ R          ┆ MAINTAINE ┆           ┆           │
│ T          ┆            ┆            ┆          ┆            ┆ R         ┆           ┆           │
│ PROTECTION ┆            ┆            ┆          ┆            ┆           ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …        ┆ …          ┆ …         ┆ …         ┆ …         │
│ DEPT OF    ┆ FARRELLY   ┆ KEVIN      ┆ null     ┆ PUTNAM     ┆ WATERSHED ┆ 67716.0   ┆ per Annum │
│ ENVIRONMEN ┆            ┆            ┆          ┆            ┆ MAINTAINE ┆           ┆           │
│ T          ┆            ┆            ┆          ┆            ┆ R         ┆           ┆           │
│ PROTECTION ┆            ┆            ┆          ┆            ┆           ┆           ┆           │
│ DEPT OF    ┆ OSTERHOUT  ┆ TIMOTHY    ┆ J        ┆ SULLIVAN   ┆ WATERSHED ┆ 67550.0   ┆ per Annum │
│ ENVIRONMEN ┆            ┆            ┆          ┆            ┆ MAINTAINE ┆           ┆           │
│ T          ┆            ┆            ┆          ┆            ┆ R         ┆           ┆           │
│ PROTECTION ┆            ┆            ┆          ┆            ┆           ┆           ┆           │
│ DEPT OF    ┆ DIPRESSI   ┆ SALVATORE  ┆ null     ┆ DUTCHESS   ┆ WATERSHED ┆ 67550.0   ┆ per Annum │
│ ENVIRONMEN ┆            ┆            ┆          ┆            ┆ MAINTAINE ┆           ┆           │
│ T          ┆            ┆            ┆          ┆            ┆ R         ┆           ┆           │
│ PROTECTION ┆            ┆            ┆          ┆            ┆           ┆           ┆           │
│ DEPT OF    ┆ VALENCHIS  ┆ LEO        ┆ A        ┆ ULSTER     ┆ WATERSHED ┆ 61818.0   ┆ per Annum │
│ ENVIRONMEN ┆ SR         ┆            ┆          ┆            ┆ MAINTAINE ┆           ┆           │
│ T          ┆            ┆            ┆          ┆            ┆ R         ┆           ┆           │
│ PROTECTION ┆            ┆            ┆          ┆            ┆           ┆           ┆           │
│ DEPT OF    ┆ RIDER JR   ┆ STEPHEN    ┆ D        ┆ ULSTER     ┆ WATERSHED ┆ 63673.0   ┆ per Annum │
│ ENVIRONMEN ┆            ┆            ┆          ┆            ┆ MAINTAINE ┆           ┆           │
│ T          ┆            ┆            ┆          ┆            ┆ R         ┆           ┆           │
│ PROTECTION ┆            ┆            ┆          ┆            ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴──────────┴────────────┴───────────┴───────────┴───────────┘

- The `str.starts_with` method checks if a substring is found at the beginning of a string.
- The `str.ends_with` method checks if a substring is found at the end of the string.

In [67]:
nyc.filter(pl.col("Title").str.to_lowercase().str.ends_with("marshal"))

shape: (1_830, 8)
┌────────────┬────────────┬────────────┬──────────┬───────────┬────────────┬───────────┬───────────┐
│ Agency     ┆ Last Name  ┆ First Name ┆ Mid Init ┆ Borough   ┆ Title      ┆ Base      ┆ Pay Basis │
│ Name       ┆ ---        ┆ ---        ┆ ---      ┆ ---       ┆ ---        ┆ Salary    ┆ ---       │
│ ---        ┆ str        ┆ str        ┆ str      ┆ str       ┆ str        ┆ ---       ┆ str       │
│ str        ┆            ┆            ┆          ┆           ┆            ┆ f64       ┆           │
╞════════════╪════════════╪════════════╪══════════╪═══════════╪════════════╪═══════════╪═══════════╡
│ FIRE       ┆ FLYNN      ┆ DANIEL     ┆ E        ┆ MANHATTAN ┆ SUPERVISIN ┆ 119596.0  ┆ per Annum │
│ DEPARTMENT ┆            ┆            ┆          ┆           ┆ G FIRE     ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ MARSHAL    ┆           ┆           │
│ FIRE       ┆ KANE       ┆ THOMAS     ┆ G        ┆ BROOKLYN  ┆ CHIEF FIRE ┆ 235462.0  ┆ per Annum │
│ DEPARTMENT ┆            ┆            ┆          ┆           ┆ MARSHAL    ┆           ┆           │
│ FIRE       ┆ DURKIN     ┆ MICHAEL    ┆ B        ┆ BROOKLYN  ┆ ASSISTANT  ┆ 215352.0  ┆ per Annum │
│ DEPARTMENT ┆            ┆            ┆          ┆           ┆ CHIEF FIRE ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ MARSHAL    ┆           ┆           │
│ FIRE       ┆ KREBS      ┆ BRIAN      ┆ M        ┆ QUEENS    ┆ SUPERVISIN ┆ 119596.0  ┆ per Annum │
│ DEPARTMENT ┆            ┆            ┆          ┆           ┆ G FIRE     ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ MARSHAL    ┆           ┆           │
│ FIRE       ┆ MCCARTHY   ┆ JOHN       ┆ J        ┆ BROOKLYN  ┆ SUPERVISIN ┆ 119596.0  ┆ per Annum │
│ DEPARTMENT ┆            ┆            ┆          ┆           ┆ G FIRE     ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ MARSHAL    ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …        ┆ …         ┆ …          ┆ …         ┆ …         │
│ FIRE       ┆ LINDELL    ┆ PETER      ┆ A        ┆ BROOKLYN  ┆ FIRE       ┆ 113781.0  ┆ per Annum │
│ DEPARTMENT ┆            ┆            ┆          ┆           ┆ MARSHAL    ┆           ┆           │
│ FIRE       ┆ MAZARAKIS  ┆ GEORGE     ┆ null     ┆ BROOKLYN  ┆ FIRE       ┆ 113781.0  ┆ per Annum │
│ DEPARTMENT ┆ JR.        ┆            ┆          ┆           ┆ MARSHAL    ┆           ┆           │
│ FIRE       ┆ COYLE      ┆ MICHAEL    ┆ D        ┆ BROOKLYN  ┆ FIRE       ┆ 113781.0  ┆ per Annum │
│ DEPARTMENT ┆            ┆            ┆          ┆           ┆ MARSHAL    ┆           ┆           │
│ FIRE       ┆ XUEREB     ┆ JOHN       ┆ J        ┆ BROOKLYN  ┆ SUPERVISIN ┆ 142449.0  ┆ per Annum │
│ DEPARTMENT ┆            ┆            ┆          ┆           ┆ G FIRE     ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ MARSHAL    ┆           ┆           │
│ FIRE       ┆ PASQUARELL ┆ MICHAEL    ┆ null     ┆ BROOKLYN  ┆ FIRE       ┆ 113781.0  ┆ per Annum │
│ DEPARTMENT ┆ O          ┆            ┆          ┆           ┆ MARSHAL    ┆           ┆           │
└────────────┴────────────┴────────────┴──────────┴───────────┴────────────┴───────────┴───────────┘

- Case-sensitivity can be an issue. There are no row values that start with a lowercase "fire".

In [ ]:
nyc.filter(pl.col("Title").str.to_lowercase().str.ends_with("marshal"))

- One solution is normalizing the text, which converts all characters to a consistent casing.
- For example, we can convert all convert all characters to lowercase, then provide a lowercase substring.
- Regular expressions (search patterns for text) are an alternative solution that we'll cover in the next lesson.

### Further Reading
- https://docs.pola.rs/user-guide/expressions/strings/#check-for-the-existence-of-a-pattern
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.contains.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.contains_any.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.starts_with.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.ends_with.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.lowercase.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.to_uppercase.html

## Regular Expressions
- A regular expression is a search pattern for text.
- A regular expression uses symbols to designate a match pattern (any digit, a character, a space, etc).
- Regular expressions can build up more complex search patterns (i.e., exactly 2 digits in a row followed by a space and any character between 'a' and 'e'").

In [68]:
nyc.head()

shape: (5, 8)
┌──────────────┬───────────┬────────────┬──────────┬──────────┬──────────────┬─────────┬───────────┐
│ Agency Name  ┆ Last Name ┆ First Name ┆ Mid Init ┆ Borough  ┆ Title        ┆ Base    ┆ Pay Basis │
│ ---          ┆ ---       ┆ ---        ┆ ---      ┆ ---      ┆ ---          ┆ Salary  ┆ ---       │
│ str          ┆ str       ┆ str        ┆ str      ┆ str      ┆ str          ┆ ---     ┆ str       │
│              ┆           ┆            ┆          ┆          ┆              ┆ f64     ┆           │
╞══════════════╪═══════════╪════════════╪══════════╪══════════╪══════════════╪═════════╪═══════════╡
│ OFFICE OF    ┆ BEREZIN   ┆ MIKHAIL    ┆ null     ┆ BROOKLYN ┆ EMERGENCY    ┆ 86005.0 ┆ per Annum │
│ EMERGENCY    ┆           ┆            ┆          ┆          ┆ PREPAREDNESS ┆         ┆           │
│ MANAGEMEN…   ┆           ┆            ┆          ┆          ┆ MANAGER      ┆         ┆           │
│ OFFICE OF    ┆ GEAGER    ┆ VERONICA   ┆ M        ┆ BROOKLYN ┆ EMERGENCY    ┆ 86005.0 ┆ per Annum │
│ EMERGENCY    ┆           ┆            ┆          ┆          ┆ PREPAREDNESS ┆         ┆           │
│ MANAGEMENT…  ┆           ┆            ┆          ┆          ┆ MANAGER      ┆         ┆           │
│ OFFICE OF    ┆ RAMANI    ┆ SHRADDHA   ┆ null     ┆ BROOKLYN ┆ EMERGENCY    ┆ 86005.0 ┆ per Annum │
│ EMERGENCY    ┆           ┆            ┆          ┆          ┆ PREPAREDNESS ┆         ┆           │
│ MANAGEME…    ┆           ┆            ┆          ┆          ┆ MANAGER      ┆         ┆           │
│ OFFICE OF    ┆ ROTTA     ┆ JONATHAN   ┆ D        ┆ BROOKLYN ┆ EMERGENCY    ┆ 86005.0 ┆ per Annum │
│ EMERGENCY    ┆           ┆            ┆          ┆          ┆ PREPAREDNESS ┆         ┆           │
│ MANAGEMENT   ┆           ┆            ┆          ┆          ┆ MANAGER      ┆         ┆           │
│ OFFICE OF    ┆ WILSON II ┆ ROBERT     ┆ P        ┆ BROOKLYN ┆ EMERGENCY    ┆ 86005.0 ┆ per Annum │
│ EMERGENCY    ┆           ┆            ┆          ┆          ┆ PREPAREDNESS ┆         ┆           │
│ MANAGEMENT   ┆           ┆            ┆          ┆          ┆ MANAGER      ┆         ┆           │
└──────────────┴───────────┴────────────┴──────────┴──────────┴──────────────┴─────────┴───────────┘

- Most string methods under `str` support regular expression arguments.
- Use raw strings for regular expressions. A raw string tells Python to interpret every character literally. 
- For example, Python will treat `\n` as a backslash followed by `n` rather than as a newline character.
- Raw strings prevent conflicts between the regular expression syntax and Python's escape characters.
- The next examples uses regex to identify any strings with _any_ digit within them.

In [78]:
nyc.filter(pl.col("Title").str.contains(r"\d")).select(
    pl.col("Title")
).to_series().to_list()[:10]

['CUSTOMER INFORMATION REPRESENTATIVE MA L 1549',
 'CUSTOMER INFORMATION REPRESENTATIVE MA L 1549',
 'CUSTOMER INFORMATION REPRESENTATIVE MA L 1549',
 'CUSTOMER INFORMATION REPRESENTATIVE MA L 1549',
 'CUSTOMER INFORMATION REPRESENTATIVE MA L 1549',
 'CUSTOMER INFORMATION REPRESENTATIVE MA L 1549',
 'LEGAL SECRETARIAL ASSISTANT - AL 1 ONLY',
 'LEGAL SECRETARIAL ASSISTANT - AL 1 ONLY',
 'LEGAL SECRETARIAL ASSISTANT - AL 1 ONLY',
 'CUSTOMER INFORMATION REPRESENTATIVE MA L 1549']

- The next example finds the strings with at least 2 whitespaces in a row.

In [80]:
nyc.filter(pl.col("Title").str.contains(r"\s{2,}")).select(
    pl.col("Title")
).to_series().to_list()[:10]

['PRINCIPAL ADMINISTRATIVE ASSOCIATE -  NON SUPVR',
 'PRINCIPAL ADMINISTRATIVE ASSOCIATE -  NON SUPVR',
 'PRINCIPAL ADMINISTRATIVE ASSOCIATE -  NON SUPVR',
 'PRINCIPAL ADMINISTRATIVE ASSOCIATE -  NON SUPVR',
 'PRINCIPAL ADMINISTRATIVE ASSOCIATE -  NON SUPVR',
 'PRINCIPAL ADMINISTRATIVE ASSOCIATE -  NON SUPVR',
 'PRINCIPAL ADMINISTRATIVE ASSOCIATE -  NON SUPVR',
 'PRINCIPAL ADMINISTRATIVE ASSOCIATE -  NON SUPVR',
 'PRINCIPAL ADMINISTRATIVE ASSOCIATE -  NON SUPVR',
 'PRINCIPAL ADMINISTRATIVE ASSOCIATE -  NON SUPVR']

### Further Reading
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.contains.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.strip_chars.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.to_titlecase.html

## Capture Groups
- A capture group is a designated chunk of the regular expression.
- Polars can extract a matched value through its capture group name.

In [82]:
nyc.select(
    pl.col("Title"),
    pl.col("Title")
    .str.extract(r"(?i)(\w+)\smechanic", group_index=0)
    .alias("mechanic_type"),
)

shape: (6_225_611, 2)
┌─────────────────────────────────┬───────────────────┐
│ Title                           ┆ mechanic_type     │
│ ---                             ┆ ---               │
│ str                             ┆ str               │
╞═════════════════════════════════╪═══════════════════╡
│ EMERGENCY PREPAREDNESS MANAGER  ┆ null              │
│ EMERGENCY PREPAREDNESS MANAGER  ┆ null              │
│ EMERGENCY PREPAREDNESS MANAGER  ┆ null              │
│ EMERGENCY PREPAREDNESS MANAGER  ┆ null              │
│ EMERGENCY PREPAREDNESS MANAGER  ┆ null              │
│ …                               ┆ …                 │
│ SUPERVISOR ELECTRICIAN          ┆ null              │
│ SUPERVISOR ELEVATOR MECHANIC    ┆ ELEVATOR MECHANIC │
│ SUPERVISOR ELEVATOR MECHANIC    ┆ ELEVATOR MECHANIC │
│ ADMINISTRATIVE HOUSING SUPERIN… ┆ null              │
│ ADMINISTRATIVE HOUSING MANAGER  ┆ null              │
└─────────────────────────────────┴───────────────────┘

- The `str.extract` method pulls out a capture group's content.
- Let's say we want to identify the various _types_ of mechanics who work in New York City
- We want to extract the _word_ before "mechanic" for entries in the `"Title"` column.
- We'll define that word before "mechanic" as one capture group.
- `(?i)` is a pattern that makes the search case-insensitive.
- `\w+` is a pattern for "1 or more word characters (`[A-Za-z0-9_]`).
- Capture group 0 will be the full match (the word characters, the space, and `mechanic`).

In [84]:
nyc.select(
    pl.col("Title"),
    pl.col("Title")
    .str.extract(r"(?i)(\w+)\smechanic", group_index=1)
    .alias("mechanic_type"),
).filter(pl.col("mechanic_type").is_not_null())

shape: (25_338, 2)
┌──────────────────────────────┬───────────────┐
│ Title                        ┆ mechanic_type │
│ ---                          ┆ ---           │
│ str                          ┆ str           │
╞══════════════════════════════╪═══════════════╡
│ RADIO REPAIR MECHANIC        ┆ REPAIR        │
│ RADIO REPAIR MECHANIC        ┆ REPAIR        │
│ RADIO REPAIR MECHANIC        ┆ REPAIR        │
│ RADIO REPAIR MECHANIC        ┆ REPAIR        │
│ RADIO REPAIR MECHANIC        ┆ REPAIR        │
│ …                            ┆ …             │
│ ELEVATOR MECHANIC            ┆ ELEVATOR      │
│ ELEVATOR MECHANIC            ┆ ELEVATOR      │
│ ELEVATOR MECHANIC            ┆ ELEVATOR      │
│ SUPERVISOR ELEVATOR MECHANIC ┆ ELEVATOR      │
│ SUPERVISOR ELEVATOR MECHANIC ┆ ELEVATOR      │
└──────────────────────────────┴───────────────┘

- Index 1 will capture the first and only capture group.
- The capture group is the content corresponding to `\w+` (one or more characters) inside the parentheses.

### Further Reading
- https://docs.pola.rs/user-guide/expressions/strings/#regex-specification
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.extract.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.strip_chars.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.to_titlecase.html

## Replacing Values

In [87]:
nyc.select(
    pl.col("Agency Name"),
    pl.col("Agency Name")
    .str.replace("OFFICE OF", "department of")
    .alias("new agency name"),
)

shape: (6_225_611, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ Agency Name                     ┆ new agency name                 │
│ ---                             ┆ ---                             │
│ str                             ┆ str                             │
╞═════════════════════════════════╪═════════════════════════════════╡
│  OFFICE OF EMERGENCY MANAGEMEN… ┆  department of EMERGENCY MANAG… │
│ OFFICE OF EMERGENCY MANAGEMENT… ┆ department of EMERGENCY MANAGE… │
│   OFFICE OF EMERGENCY MANAGEME… ┆   department of EMERGENCY MANA… │
│ OFFICE OF EMERGENCY MANAGEMENT  ┆ department of EMERGENCY MANAGE… │
│ OFFICE OF EMERGENCY MANAGEMENT  ┆ department of EMERGENCY MANAGE… │
│ …                               ┆ …                               │
│ NYC HOUSING AUTHORITY           ┆ NYC HOUSING AUTHORITY           │
│ NYC HOUSING AUTHORITY           ┆ NYC HOUSING AUTHORITY           │
│ NYC HOUSING AUTHORITY           ┆ NYC HOUSING AUTHORITY           │
│ NYC HOUSING AUTHORITY           ┆ NYC HOUSING AUTHORITY           │
│ NYC HOUSING AUTHORITY           ┆ NYC HOUSING AUTHORITY           │
└─────────────────────────────────┴─────────────────────────────────┘

- The `str.replace` method replaces the first occurrence of a string with another string.

- The `str.replace_all` method replaces _all_ occurrences of the substring.

In [92]:
nyc.select(
    pl.col("Agency Name"),
    pl.col("Agency Name").str.replace("OF", "!!").alias("replace"),
    pl.col("Agency Name").str.replace_all("OF", "!!").alias("replace all"),
)

shape: (6_225_611, 3)
┌────────────────────────────────┬────────────────────────────────┬────────────────────────────────┐
│ Agency Name                    ┆ replace                        ┆ replace all                    │
│ ---                            ┆ ---                            ┆ ---                            │
│ str                            ┆ str                            ┆ str                            │
╞════════════════════════════════╪════════════════════════════════╪════════════════════════════════╡
│ OFFICE OF EMERGENCY MANAGEMEN… ┆ !!FICE OF EMERGENCY MANAGEMEN… ┆ !!FICE !! EMERGENCY MANAGEMEN… │
│ OFFICE OF EMERGENCY            ┆ !!FICE OF EMERGENCY            ┆ !!FICE !! EMERGENCY            │
│ MANAGEMENT…                    ┆ MANAGEMENT…                    ┆ MANAGEMENT…                    │
│ OFFICE OF EMERGENCY MANAGEME…  ┆ !!FICE OF EMERGENCY MANAGEME…  ┆ !!FICE !! EMERGENCY MANAGEME…  │
│ OFFICE OF EMERGENCY MANAGEMENT ┆ !!FICE OF EMERGENCY MANAGEMENT ┆ !!FICE !! EMERGENCY MANAGEMENT │
│ OFFICE OF EMERGENCY MANAGEMENT ┆ !!FICE OF EMERGENCY MANAGEMENT ┆ !!FICE !! EMERGENCY MANAGEMENT │
│ …                              ┆ …                              ┆ …                              │
│ NYC HOUSING AUTHORITY          ┆ NYC HOUSING AUTHORITY          ┆ NYC HOUSING AUTHORITY          │
│ NYC HOUSING AUTHORITY          ┆ NYC HOUSING AUTHORITY          ┆ NYC HOUSING AUTHORITY          │
│ NYC HOUSING AUTHORITY          ┆ NYC HOUSING AUTHORITY          ┆ NYC HOUSING AUTHORITY          │
│ NYC HOUSING AUTHORITY          ┆ NYC HOUSING AUTHORITY          ┆ NYC HOUSING AUTHORITY          │
│ NYC HOUSING AUTHORITY          ┆ NYC HOUSING AUTHORITY          ┆ NYC HOUSING AUTHORITY          │
└────────────────────────────────┴────────────────────────────────┴────────────────────────────────┘

- Polars supports regular expressions as arguments.

In [94]:
nyc.select(
    pl.col("Agency Name"),
    pl.col("Agency Name").str.replace(r"(?i)em", "!!").alias("replace"),
    pl.col("Agency Name").str.replace_all(r"(?i)em", "!!").alias("replace all"),
)

shape: (6_225_611, 3)
┌────────────────────────────────┬────────────────────────────────┬────────────────────────────────┐
│ Agency Name                    ┆ replace                        ┆ replace all                    │
│ ---                            ┆ ---                            ┆ ---                            │
│ str                            ┆ str                            ┆ str                            │
╞════════════════════════════════╪════════════════════════════════╪════════════════════════════════╡
│ OFFICE OF EMERGENCY MANAGEMEN… ┆ OFFICE OF !!ERGENCY MANAGEMEN… ┆ OFFICE OF !!ERGENCY MANAG!!EN… │
│ OFFICE OF EMERGENCY            ┆ OFFICE OF !!ERGENCY            ┆ OFFICE OF !!ERGENCY            │
│ MANAGEMENT…                    ┆ MANAGEMENT…                    ┆ MANAG!!ENT…                    │
│ OFFICE OF EMERGENCY MANAGEME…  ┆ OFFICE OF !!ERGENCY MANAGEME…  ┆ OFFICE OF !!ERGENCY MANAG!!E…  │
│ OFFICE OF EMERGENCY MANAGEMENT ┆ OFFICE OF !!ERGENCY MANAGEMENT ┆ OFFICE OF !!ERGENCY MANAG!!ENT │
│ OFFICE OF EMERGENCY MANAGEMENT ┆ OFFICE OF !!ERGENCY MANAGEMENT ┆ OFFICE OF !!ERGENCY MANAG!!ENT │
│ …                              ┆ …                              ┆ …                              │
│ NYC HOUSING AUTHORITY          ┆ NYC HOUSING AUTHORITY          ┆ NYC HOUSING AUTHORITY          │
│ NYC HOUSING AUTHORITY          ┆ NYC HOUSING AUTHORITY          ┆ NYC HOUSING AUTHORITY          │
│ NYC HOUSING AUTHORITY          ┆ NYC HOUSING AUTHORITY          ┆ NYC HOUSING AUTHORITY          │
│ NYC HOUSING AUTHORITY          ┆ NYC HOUSING AUTHORITY          ┆ NYC HOUSING AUTHORITY          │
│ NYC HOUSING AUTHORITY          ┆ NYC HOUSING AUTHORITY          ┆ NYC HOUSING AUTHORITY          │
└────────────────────────────────┴────────────────────────────────┴────────────────────────────────┘

### Further Reading
- https://docs.pola.rs/user-guide/expressions/strings/#replace-a-pattern
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.replace.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.replace_all.html

## Find Longest Employee Names

In [95]:
nyc = pl.read_csv("nyc.csv")
nyc.head(2)

shape: (2, 8)
┌──────────────┬───────────┬────────────┬──────────┬──────────┬──────────────┬─────────┬───────────┐
│ Agency Name  ┆ Last Name ┆ First Name ┆ Mid Init ┆ Borough  ┆ Title        ┆ Base    ┆ Pay Basis │
│ ---          ┆ ---       ┆ ---        ┆ ---      ┆ ---      ┆ ---          ┆ Salary  ┆ ---       │
│ str          ┆ str       ┆ str        ┆ str      ┆ str      ┆ str          ┆ ---     ┆ str       │
│              ┆           ┆            ┆          ┆          ┆              ┆ f64     ┆           │
╞══════════════╪═══════════╪════════════╪══════════╪══════════╪══════════════╪═════════╪═══════════╡
│ OFFICE OF    ┆ BEREZIN   ┆ MIKHAIL    ┆ null     ┆ BROOKLYN ┆ EMERGENCY    ┆ 86005.0 ┆ per Annum │
│ EMERGENCY    ┆           ┆            ┆          ┆          ┆ PREPAREDNESS ┆         ┆           │
│ MANAGEMEN…   ┆           ┆            ┆          ┆          ┆ MANAGER      ┆         ┆           │
│ OFFICE OF    ┆ GEAGER    ┆ VERONICA   ┆ M        ┆ BROOKLYN ┆ EMERGENCY    ┆ 86005.0 ┆ per Annum │
│ EMERGENCY    ┆           ┆            ┆          ┆          ┆ PREPAREDNESS ┆         ┆           │
│ MANAGEMENT…  ┆           ┆            ┆          ┆          ┆ MANAGER      ┆         ┆           │
└──────────────┴───────────┴────────────┴──────────┴──────────┴──────────────┴─────────┴───────────┘

- The longest names appear to be missing characters at the end.
- The data would suggest that the system is capped at a 30-character length.

In [113]:
nyc.drop_nulls(subset=["First Name", "Last Name"]).select(
    pl.format(
        "{} {}",
        pl.col("First Name").str.strip_chars().str.to_titlecase(),
        pl.col("Last Name").str.strip_chars().str.to_titlecase(),
    ).alias("Full Name")
).with_columns(pl.col("Full Name").str.len_chars().alias("Name Lengths")).sort(
    pl.col("Name Lengths"), descending=True
)

shape: (6_212_027, 2)
┌────────────────────────────────┬──────────────┐
│ Full Name                      ┆ Name Lengths │
│ ---                            ┆ ---          │
│ str                            ┆ u32          │
╞════════════════════════════════╪══════════════╡
│ Maria Fernanda Rodriguez Torre ┆ 30           │
│ Vijayalakshimi Montgomery Gile ┆ 30           │
│ Michael-Jospeh Mercanti-Anthon ┆ 30           │
│ Comte Wladimir Lewis-Thomas De ┆ 30           │
│ Kathleen Marie Bradshaw Benite ┆ 30           │
│ …                              ┆ …            │
│ L Yu                           ┆ 4            │
│ C Wu                           ┆ 4            │
│ C Wu                           ┆ 4            │
│ Z Li                           ┆ 4            │
│ C Wu                           ┆ 4            │
└────────────────────────────────┴──────────────┘

### Further Reading
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.to_titlecase.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.strip_chars.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.len_chars.html