# Selectors
- The `polars` library includes a `selectors` submodule.
- `selectors` helps create more complex expressions targeting specific columns.
- The common alias for `selectors` is `cs`.

In [2]:
import polars as pl
import polars.selectors as cs

## Introducing the Dataset
- The `spotify` dataset is a collection of popular tracks on the music streaming service Spotify.

In [5]:
music = pl.read_csv("spotify_top_1000_tracks.csv", try_parse_dates=True)
music.head()

shape: (5, 6)
┌────────────────────┬─────────────┬────────────────────┬──────────────┬────────────┬──────────────┐
│ track_name         ┆ artist      ┆ album_name         ┆ release_date ┆ popularity ┆ duration_min │
│ ---                ┆ ---         ┆ ---                ┆ ---          ┆ ---        ┆ ---          │
│ str                ┆ str         ┆ str                ┆ date         ┆ i64        ┆ f64          │
╞════════════════════╪═════════════╪════════════════════╪══════════════╪════════════╪══════════════╡
│ Goo Goo Muck       ┆ The Cramps  ┆ Psychedelic Jungle ┆ 1981-01-01   ┆ 67         ┆ 3.100633     │
│ What Is Love - 7"  ┆ Haddaway    ┆ What Is Love       ┆ 1992-01-18   ┆ 66         ┆ 4.506217     │
│ Mix                ┆             ┆                    ┆              ┆            ┆              │
│ Wannabe            ┆ Spice Girls ┆ Spice              ┆ 1996-01-01   ┆ 82         ┆ 2.883767     │
│ Roses Are Red -    ┆ Aqua        ┆ Aquarium (Special  ┆ 1997-01-01   ┆ 60         ┆ 3.76555      │
│ Original Versi…    ┆             ┆ Edition)           ┆              ┆            ┆              │
│ Lollipop           ┆ Aqua        ┆ Aquarium (Special  ┆ 1997-01-01   ┆ 61         ┆ 3.610433     │
│ (Candyman)         ┆             ┆ Edition)           ┆              ┆            ┆              │
└────────────────────┴─────────────┴────────────────────┴──────────────┴────────────┴──────────────┘

- The `pl.col` function is pretty flexible by itself.
- It can target one column or multiple columns. It accepts a variety of inputs.

In [10]:
music.select(pl.col("track_name"), pl.col("artist"))

music.select(pl.col("track_name", "artist").str.to_uppercase())

shape: (975, 2)
┌─────────────────────────────────┬───────────────┐
│ track_name                      ┆ artist        │
│ ---                             ┆ ---           │
│ str                             ┆ str           │
╞═════════════════════════════════╪═══════════════╡
│ GOO GOO MUCK                    ┆ THE CRAMPS    │
│ WHAT IS LOVE - 7" MIX           ┆ HADDAWAY      │
│ WANNABE                         ┆ SPICE GIRLS   │
│ ROSES ARE RED - ORIGINAL VERSI… ┆ AQUA          │
│ LOLLIPOP (CANDYMAN)             ┆ AQUA          │
│ …                               ┆ …             │
│ BOOTS ON THE GROUND             ┆ DILLIN HOOX   │
│ THE MONSTER                     ┆ GAULLIN       │
│ ALONE                           ┆ NEWER         │
│ WHERE ARE YOU NOW               ┆ NICK GIARDINO │
│ MEET ME HALFWAY                 ┆ SANDËRO       │
└─────────────────────────────────┴───────────────┘

In [12]:
music.select(pl.col(pl.String).str.to_uppercase())

shape: (975, 3)
┌─────────────────────────────────┬───────────────┬────────────────────────────┐
│ track_name                      ┆ artist        ┆ album_name                 │
│ ---                             ┆ ---           ┆ ---                        │
│ str                             ┆ str           ┆ str                        │
╞═════════════════════════════════╪═══════════════╪════════════════════════════╡
│ GOO GOO MUCK                    ┆ THE CRAMPS    ┆ PSYCHEDELIC JUNGLE         │
│ WHAT IS LOVE - 7" MIX           ┆ HADDAWAY      ┆ WHAT IS LOVE               │
│ WANNABE                         ┆ SPICE GIRLS   ┆ SPICE                      │
│ ROSES ARE RED - ORIGINAL VERSI… ┆ AQUA          ┆ AQUARIUM (SPECIAL EDITION) │
│ LOLLIPOP (CANDYMAN)             ┆ AQUA          ┆ AQUARIUM (SPECIAL EDITION) │
│ …                               ┆ …             ┆ …                          │
│ BOOTS ON THE GROUND             ┆ DILLIN HOOX   ┆ BOOTS ON THE GROUND        │
│ THE MONSTER                     ┆ GAULLIN       ┆ THE MONSTER                │
│ ALONE                           ┆ NEWER         ┆ ALONE                      │
│ WHERE ARE YOU NOW               ┆ NICK GIARDINO ┆ WHERE ARE YOU NOW          │
│ MEET ME HALFWAY                 ┆ SANDËRO       ┆ MEET ME HALFWAY            │
└─────────────────────────────────┴───────────────┴────────────────────────────┘

- We can pass a data type to `col` to target columns by data type.

In [14]:
music.select(pl.col(pl.String))

shape: (975, 3)
┌─────────────────────────────────┬───────────────┬────────────────────────────┐
│ track_name                      ┆ artist        ┆ album_name                 │
│ ---                             ┆ ---           ┆ ---                        │
│ str                             ┆ str           ┆ str                        │
╞═════════════════════════════════╪═══════════════╪════════════════════════════╡
│ Goo Goo Muck                    ┆ The Cramps    ┆ Psychedelic Jungle         │
│ What Is Love - 7" Mix           ┆ Haddaway      ┆ What Is Love               │
│ Wannabe                         ┆ Spice Girls   ┆ Spice                      │
│ Roses Are Red - Original Versi… ┆ Aqua          ┆ Aquarium (Special Edition) │
│ Lollipop (Candyman)             ┆ Aqua          ┆ Aquarium (Special Edition) │
│ …                               ┆ …             ┆ …                          │
│ Boots On The Ground             ┆ Dillin Hoox   ┆ Boots On The Ground        │
│ The Monster                     ┆ Gaullin       ┆ The Monster                │
│ ALONE                           ┆ NEWER         ┆ ALONE                      │
│ Where Are You Now               ┆ Nick Giardino ┆ Where Are You Now          │
│ Meet Me Halfway                 ┆ Sandëro       ┆ Meet Me Halfway            │
└─────────────────────────────────┴───────────────┴────────────────────────────┘

- We can pass a regular expression to `col` to target columns by pattern match.
- Regular expressions must start with `^` and end with `$`.
- The `^` and `$` anchors mark the beginning and end of the target string.
- The `.` regex symbol matches any character.
- The `+` symbol means 1 or more of any character.
- The regex below evaluates to "look for 1 or more of any character, then the text `name` before the end of the string".
- The regex matches the two columns that end with `name`.

In [17]:
music.select(pl.col(r"^*.+name$"))

shape: (975, 2)
┌─────────────────────────────────┬────────────────────────────┐
│ track_name                      ┆ album_name                 │
│ ---                             ┆ ---                        │
│ str                             ┆ str                        │
╞═════════════════════════════════╪════════════════════════════╡
│ Goo Goo Muck                    ┆ Psychedelic Jungle         │
│ What Is Love - 7" Mix           ┆ What Is Love               │
│ Wannabe                         ┆ Spice                      │
│ Roses Are Red - Original Versi… ┆ Aquarium (Special Edition) │
│ Lollipop (Candyman)             ┆ Aquarium (Special Edition) │
│ …                               ┆ …                          │
│ Boots On The Ground             ┆ Boots On The Ground        │
│ The Monster                     ┆ The Monster                │
│ ALONE                           ┆ ALONE                      │
│ Where Are You Now               ┆ Where Are You Now          │
│ Meet Me Halfway                 ┆ Meet Me Halfway            │
└─────────────────────────────────┴────────────────────────────┘

- The `pl.exclude` function creates an expression that rejects columns.
- We can target a column by name, by type, by regular expression, and more.

In [18]:
music.select(pl.exclude(r"^*.+name$"))

shape: (975, 4)
┌───────────────┬──────────────┬────────────┬──────────────┐
│ artist        ┆ release_date ┆ popularity ┆ duration_min │
│ ---           ┆ ---          ┆ ---        ┆ ---          │
│ str           ┆ date         ┆ i64        ┆ f64          │
╞═══════════════╪══════════════╪════════════╪══════════════╡
│ The Cramps    ┆ 1981-01-01   ┆ 67         ┆ 3.100633     │
│ Haddaway      ┆ 1992-01-18   ┆ 66         ┆ 4.506217     │
│ Spice Girls   ┆ 1996-01-01   ┆ 82         ┆ 2.883767     │
│ Aqua          ┆ 1997-01-01   ┆ 60         ┆ 3.76555      │
│ Aqua          ┆ 1997-01-01   ┆ 61         ┆ 3.610433     │
│ …             ┆ …            ┆ …          ┆ …            │
│ Dillin Hoox   ┆ 2025-03-28   ┆ 44         ┆ 2.569517     │
│ Gaullin       ┆ 2025-03-28   ┆ 56         ┆ 2.290317     │
│ NEWER         ┆ 2025-04-04   ┆ 32         ┆ 3.09375      │
│ Nick Giardino ┆ 2025-04-04   ┆ 37         ┆ 2.354833     │
│ Sandëro       ┆ 2025-04-11   ┆ 4          ┆ 2.125183     │
└───────────────┴──────────────┴────────────┴──────────────┘

In [20]:
music.select(pl.exclude(pl.Int64))

shape: (975, 5)
┌──────────────────────────┬───────────────┬─────────────────────┬──────────────┬──────────────┐
│ track_name               ┆ artist        ┆ album_name          ┆ release_date ┆ duration_min │
│ ---                      ┆ ---           ┆ ---                 ┆ ---          ┆ ---          │
│ str                      ┆ str           ┆ str                 ┆ date         ┆ f64          │
╞══════════════════════════╪═══════════════╪═════════════════════╪══════════════╪══════════════╡
│ Goo Goo Muck             ┆ The Cramps    ┆ Psychedelic Jungle  ┆ 1981-01-01   ┆ 3.100633     │
│ What Is Love - 7" Mix    ┆ Haddaway      ┆ What Is Love        ┆ 1992-01-18   ┆ 4.506217     │
│ Wannabe                  ┆ Spice Girls   ┆ Spice               ┆ 1996-01-01   ┆ 2.883767     │
│ Roses Are Red - Original ┆ Aqua          ┆ Aquarium (Special   ┆ 1997-01-01   ┆ 3.76555      │
│ Versi…                   ┆               ┆ Edition)            ┆              ┆              │
│ Lollipop (Candyman)      ┆ Aqua          ┆ Aquarium (Special   ┆ 1997-01-01   ┆ 3.610433     │
│                          ┆               ┆ Edition)            ┆              ┆              │
│ …                        ┆ …             ┆ …                   ┆ …            ┆ …            │
│ Boots On The Ground      ┆ Dillin Hoox   ┆ Boots On The Ground ┆ 2025-03-28   ┆ 2.569517     │
│ The Monster              ┆ Gaullin       ┆ The Monster         ┆ 2025-03-28   ┆ 2.290317     │
│ ALONE                    ┆ NEWER         ┆ ALONE               ┆ 2025-04-04   ┆ 3.09375      │
│ Where Are You Now        ┆ Nick Giardino ┆ Where Are You Now   ┆ 2025-04-04   ┆ 2.354833     │
│ Meet Me Halfway          ┆ Sandëro       ┆ Meet Me Halfway     ┆ 2025-04-11   ┆ 2.125183     │
└──────────────────────────┴───────────────┴─────────────────────┴──────────────┴──────────────┘

In [22]:
music.select(pl.exclude(r"^.+name$"))

shape: (975, 4)
┌───────────────┬──────────────┬────────────┬──────────────┐
│ artist        ┆ release_date ┆ popularity ┆ duration_min │
│ ---           ┆ ---          ┆ ---        ┆ ---          │
│ str           ┆ date         ┆ i64        ┆ f64          │
╞═══════════════╪══════════════╪════════════╪══════════════╡
│ The Cramps    ┆ 1981-01-01   ┆ 67         ┆ 3.100633     │
│ Haddaway      ┆ 1992-01-18   ┆ 66         ┆ 4.506217     │
│ Spice Girls   ┆ 1996-01-01   ┆ 82         ┆ 2.883767     │
│ Aqua          ┆ 1997-01-01   ┆ 60         ┆ 3.76555      │
│ Aqua          ┆ 1997-01-01   ┆ 61         ┆ 3.610433     │
│ …             ┆ …            ┆ …          ┆ …            │
│ Dillin Hoox   ┆ 2025-03-28   ┆ 44         ┆ 2.569517     │
│ Gaullin       ┆ 2025-03-28   ┆ 56         ┆ 2.290317     │
│ NEWER         ┆ 2025-04-04   ┆ 32         ┆ 3.09375      │
│ Nick Giardino ┆ 2025-04-04   ┆ 37         ┆ 2.354833     │
│ Sandëro       ┆ 2025-04-11   ┆ 4          ┆ 2.125183     │
└───────────────┴──────────────┴────────────┴──────────────┘

### Further Reading
- https://docs.pola.rs/api/python/stable/reference/expressions/col.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.all.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.exclude.html

## Introducing Selectors
- The `cs` (column selectors) module has 30+ functions for specifying columns.
- The selectors can be applied anywhere expressions are expected (`select`, `filter`, `group_by`, etc)

In [25]:
music.select(cs.by_name("track_name"))

shape: (975, 1)
┌─────────────────────────────────┐
│ track_name                      │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ Goo Goo Muck                    │
│ What Is Love - 7" Mix           │
│ Wannabe                         │
│ Roses Are Red - Original Versi… │
│ Lollipop (Candyman)             │
│ …                               │
│ Boots On The Ground             │
│ The Monster                     │
│ ALONE                           │
│ Where Are You Now               │
│ Meet Me Halfway                 │
└─────────────────────────────────┘

- The `cs.by_name` selector targets a column by name.

In [27]:
music.select(cs.ends_with("name"))

shape: (975, 2)
┌─────────────────────────────────┬────────────────────────────┐
│ track_name                      ┆ album_name                 │
│ ---                             ┆ ---                        │
│ str                             ┆ str                        │
╞═════════════════════════════════╪════════════════════════════╡
│ Goo Goo Muck                    ┆ Psychedelic Jungle         │
│ What Is Love - 7" Mix           ┆ What Is Love               │
│ Wannabe                         ┆ Spice                      │
│ Roses Are Red - Original Versi… ┆ Aquarium (Special Edition) │
│ Lollipop (Candyman)             ┆ Aquarium (Special Edition) │
│ …                               ┆ …                          │
│ Boots On The Ground             ┆ Boots On The Ground        │
│ The Monster                     ┆ The Monster                │
│ ALONE                           ┆ ALONE                      │
│ Where Are You Now               ┆ Where Are You Now          │
│ Meet Me Halfway                 ┆ Meet Me Halfway            │
└─────────────────────────────────┴────────────────────────────┘

In [29]:
music.select(cs.starts_with("track"))

shape: (975, 1)
┌─────────────────────────────────┐
│ track_name                      │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ Goo Goo Muck                    │
│ What Is Love - 7" Mix           │
│ Wannabe                         │
│ Roses Are Red - Original Versi… │
│ Lollipop (Candyman)             │
│ …                               │
│ Boots On The Ground             │
│ The Monster                     │
│ ALONE                           │
│ Where Are You Now               │
│ Meet Me Halfway                 │
└─────────────────────────────────┘

- Selectors like `by_name` are not particularly helpful. Their syntax is more verbose compared to `pl.col`.
- Other selectors can simplify targeting columns. For example, the `ends_with` method is easier than passing a regex to `pl.col`.
- The next example uses `cs.ends_with` to target all columns that end with `"name"`.

- The complementary `cs.starts_with` selector targets columns that start with a prefix.

### Further Reading
- https://docs.pola.rs/user-guide/expressions/expression-expansion/#more-flexible-column-selections
- https://docs.pola.rs/api/python/stable/reference/selectors.html#polars.selectors.by_name
- https://docs.pola.rs/api/python/stable/reference/selectors.html#polars.selectors.starts_with
- https://docs.pola.rs/api/python/stable/reference/selectors.html#polars.selectors.ends_with

## Selecting by Data Type
- There are special selectors for targeting columns by data types.
- For example, `cs.numeric` will target all numeric columns (integers and floating-points).

In [30]:
music.select(cs.numeric())

shape: (975, 2)
┌────────────┬──────────────┐
│ popularity ┆ duration_min │
│ ---        ┆ ---          │
│ i64        ┆ f64          │
╞════════════╪══════════════╡
│ 67         ┆ 3.100633     │
│ 66         ┆ 4.506217     │
│ 82         ┆ 2.883767     │
│ 60         ┆ 3.76555      │
│ 61         ┆ 3.610433     │
│ …          ┆ …            │
│ 44         ┆ 2.569517     │
│ 56         ┆ 2.290317     │
│ 32         ┆ 3.09375      │
│ 37         ┆ 2.354833     │
│ 4          ┆ 2.125183     │
└────────────┴──────────────┘

In [31]:
music.select(cs.integer())

shape: (975, 1)
┌────────────┐
│ popularity │
│ ---        │
│ i64        │
╞════════════╡
│ 67         │
│ 66         │
│ 82         │
│ 60         │
│ 61         │
│ …          │
│ 44         │
│ 56         │
│ 32         │
│ 37         │
│ 4          │
└────────────┘

- `pl.col` can target columns by one or more data types but we have to explicitly write out each type.
- Polars has 5 types of integers! (`Int8`, `Int16`, `Int32`, `Int64`, `Int128`).
- The `cs.integer` selector targets all integer columns irrespective of their exact integer type.
- The `cs.float` selector targets all floating-points columns.

In [32]:
music.select(cs.float())

shape: (975, 1)
┌──────────────┐
│ duration_min │
│ ---          │
│ f64          │
╞══════════════╡
│ 3.100633     │
│ 4.506217     │
│ 2.883767     │
│ 3.76555      │
│ 3.610433     │
│ …            │
│ 2.569517     │
│ 2.290317     │
│ 3.09375      │
│ 2.354833     │
│ 2.125183     │
└──────────────┘

- Or perhaps we just want to target all numeric columns irrespective of their data type.

In [33]:
music.select(cs.numeric())

shape: (975, 2)
┌────────────┬──────────────┐
│ popularity ┆ duration_min │
│ ---        ┆ ---          │
│ i64        ┆ f64          │
╞════════════╪══════════════╡
│ 67         ┆ 3.100633     │
│ 66         ┆ 4.506217     │
│ 82         ┆ 2.883767     │
│ 60         ┆ 3.76555      │
│ 61         ┆ 3.610433     │
│ …          ┆ …            │
│ 44         ┆ 2.569517     │
│ 56         ┆ 2.290317     │
│ 32         ┆ 3.09375      │
│ 37         ┆ 2.354833     │
│ 4          ┆ 2.125183     │
└────────────┴──────────────┘

- The `cs.date`, `cs.time`, and `cs.datetime` selectors target date, time, and datetime columns.

In [34]:
music.select(cs.date())

shape: (975, 1)
┌──────────────┐
│ release_date │
│ ---          │
│ date         │
╞══════════════╡
│ 1981-01-01   │
│ 1992-01-18   │
│ 1996-01-01   │
│ 1997-01-01   │
│ 1997-01-01   │
│ …            │
│ 2025-03-28   │
│ 2025-03-28   │
│ 2025-04-04   │
│ 2025-04-04   │
│ 2025-04-11   │
└──────────────┘

- The `cs.temporal` selector targets any date/time/datetime columns.

In [37]:
music.select(cs.time())
music.select(cs.datetime())

shape: (0, 0)
┌┐
╞╡
└┘

- The `cs.alpha` selector targets columns whose names contain only alphabetic characters (a-z).
- The selector eliminates columns with underscores.
- The `cs.alphanumeric` selector targets columns whose names contain only alphabetic characters or numbers/digits.

In [39]:
music.select(cs.temporal())

shape: (975, 1)
┌──────────────┐
│ release_date │
│ ---          │
│ date         │
╞══════════════╡
│ 1981-01-01   │
│ 1992-01-18   │
│ 1996-01-01   │
│ 1997-01-01   │
│ 1997-01-01   │
│ …            │
│ 2025-03-28   │
│ 2025-03-28   │
│ 2025-04-04   │
│ 2025-04-04   │
│ 2025-04-11   │
└──────────────┘

In [38]:
music.select(cs.alpha())

shape: (975, 2)
┌───────────────┬────────────┐
│ artist        ┆ popularity │
│ ---           ┆ ---        │
│ str           ┆ i64        │
╞═══════════════╪════════════╡
│ The Cramps    ┆ 67         │
│ Haddaway      ┆ 66         │
│ Spice Girls   ┆ 82         │
│ Aqua          ┆ 60         │
│ Aqua          ┆ 61         │
│ …             ┆ …          │
│ Dillin Hoox   ┆ 44         │
│ Gaullin       ┆ 56         │
│ NEWER         ┆ 32         │
│ Nick Giardino ┆ 37         │
│ Sandëro       ┆ 4          │
└───────────────┴────────────┘

In [40]:
music.select(cs.alphanumeric())

shape: (975, 2)
┌───────────────┬────────────┐
│ artist        ┆ popularity │
│ ---           ┆ ---        │
│ str           ┆ i64        │
╞═══════════════╪════════════╡
│ The Cramps    ┆ 67         │
│ Haddaway      ┆ 66         │
│ Spice Girls   ┆ 82         │
│ Aqua          ┆ 60         │
│ Aqua          ┆ 61         │
│ …             ┆ …          │
│ Dillin Hoox   ┆ 44         │
│ Gaullin       ┆ 56         │
│ NEWER         ┆ 32         │
│ Nick Giardino ┆ 37         │
│ Sandëro       ┆ 4          │
└───────────────┴────────────┘

### Further Reading
- https://docs.pola.rs/api/python/stable/reference/selectors.html#polars.selectors.integer
- https://docs.pola.rs/api/python/stable/reference/selectors.html#polars.selectors.float
- https://docs.pola.rs/api/python/stable/reference/selectors.html#polars.selectors.numeric
- https://docs.pola.rs/api/python/stable/reference/selectors.html#polars.selectors.date
- https://docs.pola.rs/api/python/stable/reference/selectors.html#polars.selectors.time
- https://docs.pola.rs/api/python/stable/reference/selectors.html#polars.selectors.temporal
- https://docs.pola.rs/api/python/stable/reference/selectors.html#polars.selectors.alpha
- https://docs.pola.rs/api/python/stable/reference/selectors.html#polars.selectors.alphanumeric

## Selecting by Column Position

In [42]:
music.select(cs.by_index(0))

shape: (975, 1)
┌─────────────────────────────────┐
│ track_name                      │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ Goo Goo Muck                    │
│ What Is Love - 7" Mix           │
│ Wannabe                         │
│ Roses Are Red - Original Versi… │
│ Lollipop (Candyman)             │
│ …                               │
│ Boots On The Ground             │
│ The Monster                     │
│ ALONE                           │
│ Where Are You Now               │
│ Meet Me Halfway                 │
└─────────────────────────────────┘

- The `cs.by_index` selector targets columns by index position.
- Index positions start counting at 0. The first column is index 0, the second column is index 1, and so on.

In [44]:
music.select(cs.by_index(100))

ColumnNotFoundError: cannot get the 100-th column when schema has 6 columns

- Passing an invalid index will lead to a `ColumnNotFound` error.

In [45]:
music.select(cs.by_index(0, 1))

shape: (975, 2)
┌─────────────────────────────────┬───────────────┐
│ track_name                      ┆ artist        │
│ ---                             ┆ ---           │
│ str                             ┆ str           │
╞═════════════════════════════════╪═══════════════╡
│ Goo Goo Muck                    ┆ The Cramps    │
│ What Is Love - 7" Mix           ┆ Haddaway      │
│ Wannabe                         ┆ Spice Girls   │
│ Roses Are Red - Original Versi… ┆ Aqua          │
│ Lollipop (Candyman)             ┆ Aqua          │
│ …                               ┆ …             │
│ Boots On The Ground             ┆ Dillin Hoox   │
│ The Monster                     ┆ Gaullin       │
│ ALONE                           ┆ NEWER         │
│ Where Are You Now               ┆ Nick Giardino │
│ Meet Me Halfway                 ┆ Sandëro       │
└─────────────────────────────────┴───────────────┘

- Pass multiple values to target multiple columns by index.

- Negative values will extract from the end of the `DataFrame`.
- -1 pulls the last column, -3 pulls the third-to-last column and so on.

In [47]:
music.select(cs.by_index(-1))

shape: (975, 1)
┌──────────────┐
│ duration_min │
│ ---          │
│ f64          │
╞══════════════╡
│ 3.100633     │
│ 4.506217     │
│ 2.883767     │
│ 3.76555      │
│ 3.610433     │
│ …            │
│ 2.569517     │
│ 2.290317     │
│ 3.09375      │
│ 2.354833     │
│ 2.125183     │
└──────────────┘

- We can mix and match positive and negative values.
- The following targets the last column (-1), third-to-last column(-3), and the third column (2).
- Every column name must be unique so Polars will raise an exception if we target the same column twice.

In [49]:
music.select(cs.first(), cs.last())

shape: (975, 2)
┌─────────────────────────────────┬──────────────┐
│ track_name                      ┆ duration_min │
│ ---                             ┆ ---          │
│ str                             ┆ f64          │
╞═════════════════════════════════╪══════════════╡
│ Goo Goo Muck                    ┆ 3.100633     │
│ What Is Love - 7" Mix           ┆ 4.506217     │
│ Wannabe                         ┆ 2.883767     │
│ Roses Are Red - Original Versi… ┆ 3.76555      │
│ Lollipop (Candyman)             ┆ 3.610433     │
│ …                               ┆ …            │
│ Boots On The Ground             ┆ 2.569517     │
│ The Monster                     ┆ 2.290317     │
│ ALONE                           ┆ 3.09375      │
│ Where Are You Now               ┆ 2.354833     │
│ Meet Me Halfway                 ┆ 2.125183     │
└─────────────────────────────────┴──────────────┘

- The `first` and `last` selectors target the first and last columns.
- The `first` method is equivalent to `cs.by_index(0)`.
- The `last` method is equivalent to `cs.by_index(-1)`.

### Further Reading
- https://docs.pola.rs/api/python/stable/reference/selectors.html#polars.selectors.by_index
- https://docs.pola.rs/api/python/stable/reference/selectors.html#polars.selectors.first
- https://docs.pola.rs/api/python/stable/reference/selectors.html#polars.selectors.last

## Set Operations with Selectors
- Selectors from `cs` support common set operations (union, intersection, difference, symmetric difference, and complement).
- A set is an unordered collection of unique values. Python has a `set` type.
- Set operations refer to various comparison operations between two sets.

In [52]:
music.select(cs.ends_with("name") | cs.temporal())

shape: (975, 3)
┌─────────────────────────────────┬────────────────────────────┬──────────────┐
│ track_name                      ┆ album_name                 ┆ release_date │
│ ---                             ┆ ---                        ┆ ---          │
│ str                             ┆ str                        ┆ date         │
╞═════════════════════════════════╪════════════════════════════╪══════════════╡
│ Goo Goo Muck                    ┆ Psychedelic Jungle         ┆ 1981-01-01   │
│ What Is Love - 7" Mix           ┆ What Is Love               ┆ 1992-01-18   │
│ Wannabe                         ┆ Spice                      ┆ 1996-01-01   │
│ Roses Are Red - Original Versi… ┆ Aquarium (Special Edition) ┆ 1997-01-01   │
│ Lollipop (Candyman)             ┆ Aquarium (Special Edition) ┆ 1997-01-01   │
│ …                               ┆ …                          ┆ …            │
│ Boots On The Ground             ┆ Boots On The Ground        ┆ 2025-03-28   │
│ The Monster                     ┆ The Monster                ┆ 2025-03-28   │
│ ALONE                           ┆ ALONE                      ┆ 2025-04-04   │
│ Where Are You Now               ┆ Where Are You Now          ┆ 2025-04-04   │
│ Meet Me Halfway                 ┆ Meet Me Halfway            ┆ 2025-04-11   │
└─────────────────────────────────┴────────────────────────────┴──────────────┘

### Union
- We can use symbols to combine selectors. Different symbols apply different set operations.
- The `|` symbol creates a union (either/or) operation between the selectors.
- The union is the combination of two sets' values regardless of whether the value exists in one set or both.
- The next example targets columns that end with `"name"` or store temporal/datetime data (or both).

### Intersection
- The `&` symbol performs an intersection (AND). The value must exist in both sets.
- The `cs.contains` selector checks if the column name contains a substring.
- The code below targets columns that hold string values AND whose names contain `"ar"`.
- The selector excludes the `popularity` column. It holds `"ar"` but it is not a string column.

In [54]:
music.select(cs.string() & cs.contains("ar"))

shape: (975, 1)
┌───────────────┐
│ artist        │
│ ---           │
│ str           │
╞═══════════════╡
│ The Cramps    │
│ Haddaway      │
│ Spice Girls   │
│ Aqua          │
│ Aqua          │
│ …             │
│ Dillin Hoox   │
│ Gaullin       │
│ NEWER         │
│ Nick Giardino │
│ Sandëro       │
└───────────────┘

### Difference
- The `-` symbol calculates the difference between two sets.
- A difference operation removes entries from one set if they are found in the other set.
- Think of it as "subtracting" values from the set.
- The following example selects string columns _except for_ those that contain `name`.

In [57]:
music.select(cs.string() - cs.contains("art"))

shape: (975, 2)
┌─────────────────────────────────┬────────────────────────────┐
│ track_name                      ┆ album_name                 │
│ ---                             ┆ ---                        │
│ str                             ┆ str                        │
╞═════════════════════════════════╪════════════════════════════╡
│ Goo Goo Muck                    ┆ Psychedelic Jungle         │
│ What Is Love - 7" Mix           ┆ What Is Love               │
│ Wannabe                         ┆ Spice                      │
│ Roses Are Red - Original Versi… ┆ Aquarium (Special Edition) │
│ Lollipop (Candyman)             ┆ Aquarium (Special Edition) │
│ …                               ┆ …                          │
│ Boots On The Ground             ┆ Boots On The Ground        │
│ The Monster                     ┆ The Monster                │
│ ALONE                           ┆ ALONE                      │
│ Where Are You Now               ┆ Where Are You Now          │
│ Meet Me Halfway                 ┆ Meet Me Halfway            │
└─────────────────────────────────┴────────────────────────────┘

### Symmetric Difference/Exclusive Or
- The `^` (exclusive or symbol) selects columns that satisfy either one condition or the other but _not_ both.
- Equivalently, the `^` targets values that exist in the first set or the second set but not both sets.
- The next example selects columns that are either strings or contain the text `name` but not both.
- Polars excludes `track_name` and `album_name` because they are string columns that contain `"name"`.

In [59]:
music.select(cs.string() ^ cs.contains("name"))

shape: (975, 1)
┌───────────────┐
│ artist        │
│ ---           │
│ str           │
╞═══════════════╡
│ The Cramps    │
│ Haddaway      │
│ Spice Girls   │
│ Aqua          │
│ Aqua          │
│ …             │
│ Dillin Hoox   │
│ Gaullin       │
│ NEWER         │
│ Nick Giardino │
│ Sandëro       │
└───────────────┘

### Exclusion
- The `~` (tilde) symbol performs exclusion/negation.
- The selector targets the inverse of the results set.
- For example, `~cs.temporal` will select all non-temporal columns.

In [60]:
music.select(~cs.string())

shape: (975, 3)
┌──────────────┬────────────┬──────────────┐
│ release_date ┆ popularity ┆ duration_min │
│ ---          ┆ ---        ┆ ---          │
│ date         ┆ i64        ┆ f64          │
╞══════════════╪════════════╪══════════════╡
│ 1981-01-01   ┆ 67         ┆ 3.100633     │
│ 1992-01-18   ┆ 66         ┆ 4.506217     │
│ 1996-01-01   ┆ 82         ┆ 2.883767     │
│ 1997-01-01   ┆ 60         ┆ 3.76555      │
│ 1997-01-01   ┆ 61         ┆ 3.610433     │
│ …            ┆ …          ┆ …            │
│ 2025-03-28   ┆ 44         ┆ 2.569517     │
│ 2025-03-28   ┆ 56         ┆ 2.290317     │
│ 2025-04-04   ┆ 32         ┆ 3.09375      │
│ 2025-04-04   ┆ 37         ┆ 2.354833     │
│ 2025-04-11   ┆ 4          ┆ 2.125183     │
└──────────────┴────────────┴──────────────┘

- We can accomplish the same result with the `cs.exclude` function.
- The `cs.exclude` function accepts other selectors. The `pl.exclude` function will not work here.
- The next example excludes all temporal columns (date/time/datetime).

In [61]:
music.select(cs.exclude("release_date"))

shape: (975, 5)
┌──────────────────────────┬───────────────┬─────────────────────┬────────────┬──────────────┐
│ track_name               ┆ artist        ┆ album_name          ┆ popularity ┆ duration_min │
│ ---                      ┆ ---           ┆ ---                 ┆ ---        ┆ ---          │
│ str                      ┆ str           ┆ str                 ┆ i64        ┆ f64          │
╞══════════════════════════╪═══════════════╪═════════════════════╪════════════╪══════════════╡
│ Goo Goo Muck             ┆ The Cramps    ┆ Psychedelic Jungle  ┆ 67         ┆ 3.100633     │
│ What Is Love - 7" Mix    ┆ Haddaway      ┆ What Is Love        ┆ 66         ┆ 4.506217     │
│ Wannabe                  ┆ Spice Girls   ┆ Spice               ┆ 82         ┆ 2.883767     │
│ Roses Are Red - Original ┆ Aqua          ┆ Aquarium (Special   ┆ 60         ┆ 3.76555      │
│ Versi…                   ┆               ┆ Edition)            ┆            ┆              │
│ Lollipop (Candyman)      ┆ Aqua          ┆ Aquarium (Special   ┆ 61         ┆ 3.610433     │
│                          ┆               ┆ Edition)            ┆            ┆              │
│ …                        ┆ …             ┆ …                   ┆ …          ┆ …            │
│ Boots On The Ground      ┆ Dillin Hoox   ┆ Boots On The Ground ┆ 44         ┆ 2.569517     │
│ The Monster              ┆ Gaullin       ┆ The Monster         ┆ 56         ┆ 2.290317     │
│ ALONE                    ┆ NEWER         ┆ ALONE               ┆ 32         ┆ 3.09375      │
│ Where Are You Now        ┆ Nick Giardino ┆ Where Are You Now   ┆ 37         ┆ 2.354833     │
│ Meet Me Halfway          ┆ Sandëro       ┆ Meet Me Halfway     ┆ 4          ┆ 2.125183     │
└──────────────────────────┴───────────────┴─────────────────────┴────────────┴──────────────┘

In [62]:
music.select(~cs.temporal())

shape: (975, 5)
┌──────────────────────────┬───────────────┬─────────────────────┬────────────┬──────────────┐
│ track_name               ┆ artist        ┆ album_name          ┆ popularity ┆ duration_min │
│ ---                      ┆ ---           ┆ ---                 ┆ ---        ┆ ---          │
│ str                      ┆ str           ┆ str                 ┆ i64        ┆ f64          │
╞══════════════════════════╪═══════════════╪═════════════════════╪════════════╪══════════════╡
│ Goo Goo Muck             ┆ The Cramps    ┆ Psychedelic Jungle  ┆ 67         ┆ 3.100633     │
│ What Is Love - 7" Mix    ┆ Haddaway      ┆ What Is Love        ┆ 66         ┆ 4.506217     │
│ Wannabe                  ┆ Spice Girls   ┆ Spice               ┆ 82         ┆ 2.883767     │
│ Roses Are Red - Original ┆ Aqua          ┆ Aquarium (Special   ┆ 60         ┆ 3.76555      │
│ Versi…                   ┆               ┆ Edition)            ┆            ┆              │
│ Lollipop (Candyman)      ┆ Aqua          ┆ Aquarium (Special   ┆ 61         ┆ 3.610433     │
│                          ┆               ┆ Edition)            ┆            ┆              │
│ …                        ┆ …             ┆ …                   ┆ …          ┆ …            │
│ Boots On The Ground      ┆ Dillin Hoox   ┆ Boots On The Ground ┆ 44         ┆ 2.569517     │
│ The Monster              ┆ Gaullin       ┆ The Monster         ┆ 56         ┆ 2.290317     │
│ ALONE                    ┆ NEWER         ┆ ALONE               ┆ 32         ┆ 3.09375      │
│ Where Are You Now        ┆ Nick Giardino ┆ Where Are You Now   ┆ 37         ┆ 2.354833     │
│ Meet Me Halfway          ┆ Sandëro       ┆ Meet Me Halfway     ┆ 4          ┆ 2.125183     │
└──────────────────────────┴───────────────┴─────────────────────┴────────────┴──────────────┘

- Selectors can utilize other selectors.
- The next example excludes columns that fall in the set of string columns that do not contain `"art"`.
- `track_name` and `album_name` are string columns that do not contain `"art"`.
- Polars thus excludes `track_name` and `album_name` from the `DataFrame`.

In [63]:
music.select(cs.exclude(cs.temporal()))

shape: (975, 5)
┌──────────────────────────┬───────────────┬─────────────────────┬────────────┬──────────────┐
│ track_name               ┆ artist        ┆ album_name          ┆ popularity ┆ duration_min │
│ ---                      ┆ ---           ┆ ---                 ┆ ---        ┆ ---          │
│ str                      ┆ str           ┆ str                 ┆ i64        ┆ f64          │
╞══════════════════════════╪═══════════════╪═════════════════════╪════════════╪══════════════╡
│ Goo Goo Muck             ┆ The Cramps    ┆ Psychedelic Jungle  ┆ 67         ┆ 3.100633     │
│ What Is Love - 7" Mix    ┆ Haddaway      ┆ What Is Love        ┆ 66         ┆ 4.506217     │
│ Wannabe                  ┆ Spice Girls   ┆ Spice               ┆ 82         ┆ 2.883767     │
│ Roses Are Red - Original ┆ Aqua          ┆ Aquarium (Special   ┆ 60         ┆ 3.76555      │
│ Versi…                   ┆               ┆ Edition)            ┆            ┆              │
│ Lollipop (Candyman)      ┆ Aqua          ┆ Aquarium (Special   ┆ 61         ┆ 3.610433     │
│                          ┆               ┆ Edition)            ┆            ┆              │
│ …                        ┆ …             ┆ …                   ┆ …          ┆ …            │
│ Boots On The Ground      ┆ Dillin Hoox   ┆ Boots On The Ground ┆ 44         ┆ 2.569517     │
│ The Monster              ┆ Gaullin       ┆ The Monster         ┆ 56         ┆ 2.290317     │
│ ALONE                    ┆ NEWER         ┆ ALONE               ┆ 32         ┆ 3.09375      │
│ Where Are You Now        ┆ Nick Giardino ┆ Where Are You Now   ┆ 37         ┆ 2.354833     │
│ Meet Me Halfway          ┆ Sandëro       ┆ Meet Me Halfway     ┆ 4          ┆ 2.125183     │
└──────────────────────────┴───────────────┴─────────────────────┴────────────┴──────────────┘

In [64]:
music.select(cs.exclude(cs.string() - cs.contains("art")))

shape: (975, 4)
┌───────────────┬──────────────┬────────────┬──────────────┐
│ artist        ┆ release_date ┆ popularity ┆ duration_min │
│ ---           ┆ ---          ┆ ---        ┆ ---          │
│ str           ┆ date         ┆ i64        ┆ f64          │
╞═══════════════╪══════════════╪════════════╪══════════════╡
│ The Cramps    ┆ 1981-01-01   ┆ 67         ┆ 3.100633     │
│ Haddaway      ┆ 1992-01-18   ┆ 66         ┆ 4.506217     │
│ Spice Girls   ┆ 1996-01-01   ┆ 82         ┆ 2.883767     │
│ Aqua          ┆ 1997-01-01   ┆ 60         ┆ 3.76555      │
│ Aqua          ┆ 1997-01-01   ┆ 61         ┆ 3.610433     │
│ …             ┆ …            ┆ …          ┆ …            │
│ Dillin Hoox   ┆ 2025-03-28   ┆ 44         ┆ 2.569517     │
│ Gaullin       ┆ 2025-03-28   ┆ 56         ┆ 2.290317     │
│ NEWER         ┆ 2025-04-04   ┆ 32         ┆ 3.09375      │
│ Nick Giardino ┆ 2025-04-04   ┆ 37         ┆ 2.354833     │
│ Sandëro       ┆ 2025-04-11   ┆ 4          ┆ 2.125183     │
└───────────────┴──────────────┴────────────┴──────────────┘

### Further Reading
- https://docs.pola.rs/user-guide/expressions/expression-expansion/#combining-selectors-with-set-operations
- https://docs.pola.rs/api/python/stable/reference/selectors.html#polars.selectors.string
- https://docs.pola.rs/api/python/stable/reference/selectors.html#polars.selectors.contains
- https://docs.pola.rs/api/python/stable/reference/selectors.html#polars.selectors.temporal

## Complete List of Selectors
- Docs: https://docs.pola.rs/user-guide/expressions/expression-expansion/#complete-reference